Repository kruize/autotune, pull requests merged in 2023-04, with the labels that each got.

#686 Database design document.
  design/KruizeDatabaseDesign.md
Labels: database

#702 Fix issues in Measurement_duration
  Dockerfile.autotune
  src/main/java/com/autotune/analyzer/experiment/ExperimentResultValidation.java
  src/main/java/com/autotune/analyzer/kruizeObject/KruizeObject.java
  src/main/java/com/autotune/analyzer/serviceObjects/Converters.java
  src/main/java/com/autotune/analyzer/services/CreateExperiment.java
  src/main/java/com/autotune/analyzer/utils/AnalyzerErrorConstants.java
Labels: bug, remote_monitoring

#699 Add note in docs to use timeseries order for update results API
  design/MonitoringModeAPI.md
Labels: documentation, recommendation

#674 db tables created and stored for create and update results api.
  manifests/crc/BYODB-installation/minikube/kruize-crc-minikube.yaml
  manifests/crc/BYODB-installation/openshift/kruize-crc-openshift.yaml
  manifests/crc/default-db-included-installation/minikube/kruize-crc-minikube.yaml
  manifests/crc/default-db-included-installation/openshift/kruize-crc-openshift.yaml
  pom.xml
  src/main/java/com/autotune/analyzer/experiment/ExperimentInterface.java
  src/main/java/com/autotune/analyzer/experiment/ExperimentInterfaceImpl.java
  src/main/java/com/autotune/analyzer/kruizeObject/KruizeObject.java
  src/main/java/com/autotune/analyzer/services/CreateExperiment.java
  src/main/java/com/autotune/analyzer/services/UpdateResults.java
  src/main/java/com/autotune/analyzer/utils/AnalyzerConstants.java
  src/main/java/com/autotune/analyzer/workerimpl/CreateExperimentManager.java
  src/main/java/com/autotune/analyzer/workerimpl/UpdateResultManager.java
  src/main/java/com/autotune/common/data/metrics/MetricAggregationInfoResults.java
  src/main/java/com/autotune/common/data/metrics/MetricPercentileResults.java
  src/main/java/com/autotune/database/dao/ExperimentDAO.java
  src/main/java/com/autotune/database/dao/ExperimentDAOImpl.java
  src/main/java/com/autotune/database/helper/DBHelpers.java
  src/main/java/com/autotune/database/helper/GenrateExperimentID.java
  src/main/java/com/autotune/database/table/KruizeExperimentEntry.java
  src/main/java/com/autotune/database/table/KruizeRecommendationEntry.java
  src/main/java/com/autotune/database/table/KruizeResultsEntry.java
  src/main/java/com/autotune/operator/InitializeDeployment.java
  src/main/java/com/autotune/operator/KruizeDeploymentInfo.java
  src/main/java/com/autotune/service/InitiateListener.java
  src/main/java/com/autotune/utils/ServerContext.java
  src/main/java/com/autotune/utils/Utils.java
  src/main/resources/hibernate.cfg.xml
Labels: database

#708 Fix the deployment type issue
  src/main/java/com/autotune/analyzer/experiment/ExperimentResultValidation.java
  src/main/java/com/autotune/analyzer/experiment/ExperimentValidation.java
  src/main/java/com/autotune/utils/KruizeConstants.java
Labels: bug, remote_monitoring

#710 fixes the typo in percentile call
  src/main/java/com/autotune/analyzer/recommendations/engine/DurationBasedRecommendationEngine.java
Labels: recommendation

#713 Remove result data from Kruize Object
  src/main/java/com/autotune/analyzer/experiment/ExperimentInterfaceImpl.java
  src/main/java/com/autotune/analyzer/experiment/ExperimentResultValidation.java
  src/main/java/com/autotune/analyzer/kruizeObject/KruizeObject.java
Labels: remote_monitoring, code_cleanup/refactor

#721 Fix timestamp naming
  src/main/java/com/autotune/analyzer/experiment/ExperimentInterfaceImpl.java
  src/main/java/com/autotune/analyzer/experiment/ExperimentResultValidation.java
  src/main/java/com/autotune/analyzer/serviceObjects/Converters.java
  src/main/java/com/autotune/common/data/result/ContainerData.java
  src/main/java/com/autotune/common/data/result/ExperimentResultData.java
  src/main/java/com/autotune/common/data/result/IntervalResults.java
  src/main/java/com/autotune/database/helper/DBHelpers.java
  src/main/java/com/autotune/experimentManager/utils/EMUtil.java
  src/main/java/com/autotune/utils/KruizeConstants.java
Labels: code_cleanup/refactor

#740 Bump mvp_demo to 0.0.13_mvp
  pom.xml
  scripts/common_utils.sh
Labels: release

#741 Spelling fix in yaml and MD files
  design/KruizeConfigurationProcedure.md
  manifests/crc/BYODB-installation/minikube/kruize-crc-minikube.yaml
  manifests/crc/BYODB-installation/openshift/kruize-crc-openshift.yaml
  manifests/crc/default-db-included-installation/minikube/kruize-crc-minikube.yaml
  manifests/crc/default-db-included-installation/openshift/kruize-crc-openshift.yaml
Labels: bug, remote_monitoring

#748 Changed config values to default.
  manifests/crc/BYODB-installation/minikube/kruize-crc-minikube.yaml
  manifests/crc/BYODB-installation/openshift/kruize-crc-openshift.yaml
  manifests/crc/default-db-included-installation/minikube/kruize-crc-minikube.yaml
  manifests/crc/default-db-included-installation/openshift/kruize-crc-openshift.yaml
Labels: database

#750 Fix updateResults duration check
  src/main/java/com/autotune/analyzer/experiment/ExperimentResultValidation.java
  src/main/java/com/autotune/analyzer/utils/AnalyzerErrorConstants.java
  src/main/java/com/autotune/common/data/result/IntervalResults.java
  src/main/java/com/autotune/utils/KruizeConstants.java
Labels: bug

#753 Fix error message for invalid measurement duration
  src/main/java/com/autotune/analyzer/utils/AnalyzerErrorConstants.java
Labels: bug

#758 List experiments fix
  src/main/java/com/autotune/analyzer/experiment/ExperimentValidation.java
  src/main/java/com/autotune/analyzer/serviceObjects/Converters.java
  src/main/java/com/autotune/analyzer/serviceObjects/CreateExperimentAPIObject.java
  src/main/java/com/autotune/analyzer/services/CreateExperiment.java
Labels: bug

#761 Remove watcher exception from log.
  src/main/java/com/autotune/common/target/kubernetes/service/impl/KubernetesServicesImpl.java
Labels: bug

#763 Remove unnecessary debug logs
  src/main/java/com/autotune/analyzer/experiment/ExperimentInterfaceImpl.java
  src/main/java/com/autotune/analyzer/performanceProfiles/PerformanceProfileInterface/DefaultImpl.java
  src/main/java/com/autotune/analyzer/performanceProfiles/PerformanceProfileValidation.java
  src/main/java/com/autotune/analyzer/performanceProfiles/utils/PerformanceProfileUtil.java
  src/main/java/com/autotune/analyzer/serviceObjects/Converters.java
  src/main/java/com/autotune/analyzer/utils/EvalExParser.java
  src/main/java/com/autotune/common/datasource/DataSourceFactory.java
  src/main/java/com/autotune/common/datasource/PrometheusDataSource.java
  src/main/java/com/autotune/database/helper/DBHelpers.java
  src/main/java/com/autotune/operator/KruizeOperator.java
  src/main/java/com/autotune/utils/HttpUtils.java
Labels: bug, code_cleanup/refactor

#759 Fix recommendation exceptions
  src/main/java/com/autotune/analyzer/experiment/ExperimentInitiator.java
  src/main/java/com/autotune/analyzer/performanceProfiles/PerformanceProfileInterface/DefaultImpl.java
  src/main/java/com/autotune/analyzer/performanceProfiles/PerformanceProfileInterface/PerfProfileInterface.java
  src/main/java/com/autotune/analyzer/performanceProfiles/PerformanceProfileInterface/ResourceOptimizationOpenshiftImpl.java
  src/main/java/com/autotune/analyzer/recommendations/GenerateRecommendation.java
  src/main/java/com/autotune/analyzer/recommendations/engine/DurationBasedRecommendationEngine.java
  src/main/java/com/autotune/analyzer/recommendations/engine/KruizeRecommendationEngine.java
  src/main/java/com/autotune/analyzer/recommendations/engine/ProfileBasedRecommendationEngine.java
  src/main/java/com/autotune/analyzer/recommendations/subCategory/DurationBasedRecommendationSubCategory.java
  src/main/java/com/autotune/analyzer/recommendations/subCategory/ProfileBasedRecommendationSubCategory.java
  src/main/java/com/autotune/analyzer/recommendations/subCategory/RecommendationSubCategory.java
  src/main/java/com/autotune/analyzer/serviceObjects/Converters.java
  src/main/java/com/autotune/analyzer/services/ListRecommendation.java
  src/main/java/com/autotune/analyzer/services/UpdateResults.java
  src/main/java/com/autotune/analyzer/utils/AnalyzerConstants.java
  src/main/java/com/autotune/database/helper/DBHelpers.java
  src/main/java/com/autotune/database/service/ExperimentDBService.java
Labels: bug, recommendation

#767 Algo: Handle low CPU usage better
  src/main/java/com/autotune/analyzer/experiment/ExperimentInitiator.java
  src/main/java/com/autotune/analyzer/recommendations/engine/DurationBasedRecommendationEngine.java
  src/main/java/com/autotune/analyzer/utils/AnalyzerConstants.java
Labels: recommendation

#756 Fetch recommendations from DB and save to local storage
  src/main/java/com/autotune/analyzer/exceptions/InvalidConversionOfRecommendationEntryException.java
  src/main/java/com/autotune/analyzer/experiment/ExperimentInterface.java
  src/main/java/com/autotune/analyzer/experiment/ExperimentInterfaceImpl.java
  src/main/java/com/autotune/analyzer/recommendations/Recommendation.java
  src/main/java/com/autotune/analyzer/recommendations/RecommendationConfigItem.java
  src/main/java/com/autotune/analyzer/serviceObjects/ContainerAPIObject.java
  src/main/java/com/autotune/analyzer/serviceObjects/Converters.java
  src/main/java/com/autotune/analyzer/serviceObjects/KubernetesAPIObject.java
  src/main/java/com/autotune/analyzer/utils/AnalyzerConstants.java
  src/main/java/com/autotune/analyzer/utils/AnalyzerErrorConstants.java
  src/main/java/com/autotune/database/dao/ExperimentDAO.java
  src/main/java/com/autotune/database/dao/ExperimentDAOImpl.java
  src/main/java/com/autotune/database/helper/DBConstants.java
  src/main/java/com/autotune/database/helper/DBHelpers.java
  src/main/java/com/autotune/database/service/ExperimentDBService.java
  src/main/java/com/autotune/utils/KruizeConstants.java
Labels: database, recommendation

#775 Bump remote monitoring to 0.0.13_rm
  manifests/crc/BYODB-installation/minikube/kruize-crc-minikube.yaml
  manifests/crc/BYODB-installation/openshift/kruize-crc-openshift.yaml
  manifests/crc/default-db-included-installation/minikube/kruize-crc-minikube.yaml
  manifests/crc/default-db-included-installation/openshift/kruize-crc-openshift.yaml
Labels: release
