Repository kruize/autotune, pull requests merged in 2023-09, with the labels that each got.

#903 Rename duration based to cost
  .gitignore
  design/APISamples.md
  design/MonitoringModeAPI.md
  src/main/java/com/autotune/analyzer/performanceProfiles/PerformanceProfileInterface/ResourceOptimizationOpenshiftImpl.java
  src/main/java/com/autotune/analyzer/recommendations/GenerateRecommendation.java
  src/main/java/com/autotune/analyzer/recommendations/RecommendationConstants.java
  src/main/java/com/autotune/analyzer/recommendations/engine/CostRecommendationEngine.java
  src/main/java/com/autotune/analyzer/recommendations/subCategory/CostRecommendationSubCategory.java
  src/main/java/com/autotune/analyzer/utils/AnalyzerConstants.java
  src/main/java/com/autotune/utils/KruizeConstants.java
  tests/scripts/remote_monitoring_tests/helpers/list_reco_json_schema.py
  tests/scripts/remote_monitoring_tests/helpers/utils.py
  tests/scripts/remote_monitoring_tests/rest_apis/test_e2e_workflow.py
  tests/scripts/remote_monitoring_tests/rest_apis/test_list_recommendations.py
  tests/scripts/remote_monitoring_tests/rest_apis/test_update_recommendations.py
Labels: remote_monitoring, recommendation

#927 ListRecommendation JSON structure changes
  src/main/java/com/autotune/analyzer/performanceProfiles/PerformanceProfileInterface/ResourceOptimizationOpenshiftImpl.java
  src/main/java/com/autotune/analyzer/recommendations/ContainerRecommendations.java
  src/main/java/com/autotune/analyzer/recommendations/GenerateRecommendation.java
  src/main/java/com/autotune/analyzer/recommendations/RecommendationConstants.java
  src/main/java/com/autotune/analyzer/recommendations/RecommendationNotification.java
  src/main/java/com/autotune/analyzer/recommendations/engine/CostRecommendationEngine.java
  src/main/java/com/autotune/analyzer/recommendations/engine/KruizeRecommendationEngine.java
  src/main/java/com/autotune/analyzer/recommendations/engine/PerformanceRecommendationEngine.java
  src/main/java/com/autotune/analyzer/recommendations/objects/MappedRecommendationForEngine.java
  src/main/java/com/autotune/analyzer/recommendations/objects/MappedRecommendationForTerm.java
  src/main/java/com/autotune/analyzer/recommendations/objects/MappedRecommendationForTimestamp.java
  src/main/java/com/autotune/analyzer/recommendations/objects/TermRecommendations.java
  src/main/java/com/autotune/analyzer/recommendations/utils/RecommendationUtils.java
  src/main/java/com/autotune/analyzer/serviceObjects/Converters.java
  src/main/java/com/autotune/analyzer/utils/AnalyzerConstants.java
  src/main/java/com/autotune/database/helper/DBHelpers.java
  src/main/java/com/autotune/utils/KruizeConstants.java
Labels: remote_monitoring, API

#930 add changes to include clusterName in the queries
  src/main/java/com/autotune/analyzer/serviceObjects/verification/validators/ExperimentNameExistValidator.java
  src/main/java/com/autotune/analyzer/services/UpdateRecommendations.java
  src/main/java/com/autotune/database/dao/ExperimentDAO.java
  src/main/java/com/autotune/database/dao/ExperimentDAOImpl.java
  src/main/java/com/autotune/database/helper/DBConstants.java
  src/main/java/com/autotune/database/service/ExperimentDBService.java
  src/main/java/com/autotune/database/table/KruizeResultsEntry.java
Labels: database

#931 Add indices for clusterName and interval endtime in results table
  src/main/java/com/autotune/database/table/KruizeResultsEntry.java
Labels: database

#937 Add Jobs for DB Partition and Retention changes
  Dockerfile.autotune
  manifests/crc/BYODB-installation/openshift/kruize-crc-openshift.yaml
  manifests/crc/default-db-included-installation/minikube/kruize-crc-minikube.yaml
  manifests/crc/default-db-included-installation/openshift/kruize-crc-openshift.yaml
  migrations/kruize_experiments_ddl.sql
  pom.xml
  src/main/java/com/autotune/Autotune.java
  src/main/java/com/autotune/analyzer/serviceObjects/verification/validators/ExperimentNameExistValidator.java
  src/main/java/com/autotune/analyzer/serviceObjects/verification/validators/KubernetesElementsValidator.java
  src/main/java/com/autotune/analyzer/serviceObjects/verification/validators/PerformanceProfileValidator.java
  src/main/java/com/autotune/analyzer/serviceObjects/verification/validators/TimeDifferenceValidator.java
  src/main/java/com/autotune/analyzer/services/UpdateRecommendations.java
  src/main/java/com/autotune/analyzer/services/UpdateResults.java
  src/main/java/com/autotune/analyzer/utils/AnalyzerConstants.java
  src/main/java/com/autotune/database/dao/ExperimentDAO.java
  src/main/java/com/autotune/database/dao/ExperimentDAOImpl.java
  src/main/java/com/autotune/database/helper/DBConstants.java
  src/main/java/com/autotune/database/helper/DBHelpers.java
  src/main/java/com/autotune/database/table/KruizeRecommendationEntry.java
  src/main/java/com/autotune/database/table/KruizeResultsEntry.java
  src/main/java/com/autotune/jobs/CreatePartition.java
  src/main/java/com/autotune/jobs/RetentionPartition.java
Labels: remote_monitoring, database, db_scalability

#946 Fix DB partition issue
  src/main/java/com/autotune/database/dao/ExperimentDAOImpl.java
  src/main/java/com/autotune/database/helper/DBConstants.java
Labels: bug, db_scalability

#945 Fix Performance Profile issues
  design/NotificationCodes.md
  src/main/java/com/autotune/analyzer/performanceProfiles/PerformanceProfileInterface/ResourceOptimizationOpenshiftImpl.java
  src/main/java/com/autotune/analyzer/recommendations/RecommendationConstants.java
  src/main/java/com/autotune/analyzer/recommendations/engine/CostRecommendationEngine.java
  src/main/java/com/autotune/analyzer/recommendations/engine/PerformanceRecommendationEngine.java
  src/main/java/com/autotune/analyzer/recommendations/objects/MappedRecommendationForEngine.java
  src/main/java/com/autotune/analyzer/recommendations/utils/RecommendationUtils.java
  src/main/java/com/autotune/analyzer/utils/AnalyzerConstants.java
  src/main/java/com/autotune/utils/KruizeConstants.java
Labels: bug

#948 Update Partition Creation Strategy
  src/main/java/com/autotune/database/dao/ExperimentDAO.java
  src/main/java/com/autotune/database/dao/ExperimentDAOImpl.java
Labels: db_scalability

#955 Bump remote_monitoring to 0.0.19_rm
  manifests/crc/BYODB-installation/minikube/kruize-crc-minikube.yaml
  manifests/crc/BYODB-installation/openshift/kruize-crc-openshift.yaml
  manifests/crc/default-db-included-installation/minikube/kruize-crc-minikube.yaml
  manifests/crc/default-db-included-installation/openshift/kruize-crc-openshift.yaml
Labels: release

#963 Cron job for DB Partition
  manifests/crc/default-db-included-installation/minikube/kruize-crc-minikube.yaml
  manifests/crc/default-db-included-installation/openshift/kruize-crc-openshift.yaml
  pom.xml
  scripts/common_utils.sh
  src/main/java/com/autotune/Autotune.java
  src/main/java/com/autotune/database/dao/ExperimentDAOImpl.java
  src/main/java/com/autotune/database/helper/DBConstants.java
  src/main/java/com/autotune/jobs/CreatePartition.java
Labels: enhancement, database, db_scalability

#969 Fix term threshold
  src/main/java/com/autotune/analyzer/recommendations/RecommendationConstants.java
  src/main/java/com/autotune/analyzer/recommendations/engine/DurationBasedRecommendationEngine.java
Labels: remote_monitoring

#972 Bump remote_monitoring to 0.0.19.2_rm
  manifests/crc/BYODB-installation/minikube/kruize-crc-minikube.yaml
  manifests/crc/BYODB-installation/openshift/kruize-crc-openshift.yaml
  manifests/crc/default-db-included-installation/minikube/kruize-crc-minikube.yaml
  manifests/crc/default-db-included-installation/openshift/kruize-crc-openshift.yaml
  pom.xml
Labels: release
