Repository kruize/autotune, pull requests merged in 2023-10, with the labels that each got.

#975 Test Perf Section Changes
  tests/scripts/remote_monitoring_tests/helpers/list_reco_json_schema.py
  tests/scripts/remote_monitoring_tests/helpers/utils.py
  tests/scripts/remote_monitoring_tests/rest_apis/test_e2e_workflow.py
Labels: test

#984 Bump base image (ubi-minimal) version 8.7 -> 8.8
  Dockerfile.autotune
Labels: must_fix

#1004 Suppress and update error logs
  src/main/java/com/autotune/analyzer/exceptions/KruizeErrorHandler.java
  src/main/java/com/autotune/analyzer/services/CreateExperiment.java
  src/main/java/com/autotune/analyzer/services/UpdateResults.java
Labels: code_cleanup/refactor

#1005 Add validation for the metrics data
  src/main/java/com/autotune/analyzer/serviceObjects/Converters.java
  src/main/java/com/autotune/analyzer/serviceObjects/verification/validators/KubernetesElementsValidator.java
  src/main/java/com/autotune/analyzer/utils/AnalyzerErrorConstants.java
Labels: bug

#1011 Bump remote monitoring release to 0.0.19.4
  manifests/crc/BYODB-installation/minikube/kruize-crc-minikube.yaml
  manifests/crc/BYODB-installation/openshift/kruize-crc-openshift.yaml
  manifests/crc/default-db-included-installation/minikube/kruize-crc-minikube.yaml
  manifests/crc/default-db-included-installation/openshift/kruize-crc-openshift.yaml
  pom.xml
Labels: release
