Repository kruize/autotune, pull requests merged in 2023-08, with the labels that each got.

#828 Add Performance profile table in the DB
  src/main/java/com/autotune/analyzer/experiment/ExperimentResultValidation.java
  src/main/java/com/autotune/analyzer/experiment/ExperimentValidation.java
  src/main/java/com/autotune/analyzer/performanceProfiles/PerformanceProfile.java
  src/main/java/com/autotune/analyzer/performanceProfiles/PerformanceProfileValidation.java
  src/main/java/com/autotune/analyzer/performanceProfiles/utils/PerformanceProfileUtil.java
  src/main/java/com/autotune/analyzer/services/PerformanceProfileService.java
  src/main/java/com/autotune/analyzer/services/UpdateResults.java
  src/main/java/com/autotune/database/dao/ExperimentDAO.java
  src/main/java/com/autotune/database/dao/ExperimentDAOImpl.java
  src/main/java/com/autotune/database/helper/DBConstants.java
  src/main/java/com/autotune/database/helper/DBHelpers.java
  src/main/java/com/autotune/database/helper/GenerateExperimentID.java
  src/main/java/com/autotune/database/init/KruizeHibernateUtil.java
  src/main/java/com/autotune/database/service/ExperimentDBService.java
  src/main/java/com/autotune/database/table/KruizeExperimentEntry.java
  src/main/java/com/autotune/database/table/KruizePerformanceProfileEntry.java
Labels: bug, enhancement

#825 updateRecommendation API.
  src/main/java/com/autotune/analyzer/Analyzer.java
  src/main/java/com/autotune/analyzer/serviceObjects/Converters.java
  src/main/java/com/autotune/analyzer/services/ListExperiments.java
  src/main/java/com/autotune/analyzer/services/UpdateRecommendations.java
  src/main/java/com/autotune/analyzer/services/UpdateResults.java
  src/main/java/com/autotune/analyzer/utils/AnalyzerErrorConstants.java
  src/main/java/com/autotune/common/k8sObjects/TrialSettings.java
  src/main/java/com/autotune/database/dao/ExperimentDAO.java
  src/main/java/com/autotune/database/dao/ExperimentDAOImpl.java
  src/main/java/com/autotune/database/helper/DBConstants.java
  src/main/java/com/autotune/database/service/ExperimentDBService.java
  src/main/java/com/autotune/utils/KruizeConstants.java
  src/main/java/com/autotune/utils/ServerContext.java
  src/main/java/com/autotune/utils/Utils.java
Labels: API

#855 Get data to generate recommendation
  src/main/java/com/autotune/analyzer/experiment/ExperimentInitiator.java
  src/main/java/com/autotune/analyzer/experiment/ExperimentResultValidation.java
  src/main/java/com/autotune/analyzer/performanceProfiles/PerformanceProfileInterface/DefaultImpl.java
  src/main/java/com/autotune/analyzer/performanceProfiles/PerformanceProfileInterface/PerfProfileInterface.java
  src/main/java/com/autotune/analyzer/performanceProfiles/PerformanceProfileInterface/ResourceOptimizationOpenshiftImpl.java
  src/main/java/com/autotune/analyzer/services/ListExperiments.java
  src/main/java/com/autotune/analyzer/services/UpdateRecommendations.java
  src/main/java/com/autotune/analyzer/services/UpdateResults.java
  src/main/java/com/autotune/database/dao/ExperimentDAO.java
  src/main/java/com/autotune/database/dao/ExperimentDAOImpl.java
  src/main/java/com/autotune/database/helper/DBConstants.java
  src/main/java/com/autotune/database/helper/DBHelpers.java
  src/main/java/com/autotune/database/service/ExperimentDBService.java
Labels: API

#861 Update recommendation using date range
  src/main/java/com/autotune/analyzer/experiment/ExperimentInterfaceImpl.java
  src/main/java/com/autotune/analyzer/performanceProfiles/PerformanceProfileInterface/ResourceOptimizationOpenshiftImpl.java
  src/main/java/com/autotune/analyzer/recommendations/Recommendation.java
  src/main/java/com/autotune/analyzer/recommendations/engine/DurationBasedRecommendationEngine.java
  src/main/java/com/autotune/analyzer/services/UpdateRecommendations.java
  src/main/java/com/autotune/analyzer/utils/AnalyzerErrorConstants.java
  src/main/java/com/autotune/database/dao/ExperimentDAO.java
  src/main/java/com/autotune/database/dao/ExperimentDAOImpl.java
  src/main/java/com/autotune/database/helper/DBConstants.java
  src/main/java/com/autotune/database/service/ExperimentDBService.java
  src/main/java/com/autotune/operator/KruizeDeploymentInfo.java
Labels: API

#836 Test script for updateRecommendation API
  tests/scripts/quickTestScalability.py
  tests/scripts/remote_monitoring_tests/helpers/kruize.py
  tests/scripts/remote_monitoring_tests/helpers/utils.py
  tests/scripts/remote_monitoring_tests/remote_monitoring_tests.sh
  tests/scripts/remote_monitoring_tests/rest_apis/test_create_experiment.py
  tests/scripts/remote_monitoring_tests/rest_apis/test_e2e_workflow.py
  tests/scripts/remote_monitoring_tests/rest_apis/test_list_recommendations.py
  tests/scripts/remote_monitoring_tests/rest_apis/test_update_recommendations.py
  tests/scripts/remote_monitoring_tests/rest_apis/test_update_results.py
  tests/scripts/rosSimulationScalabilityTest.py
  tests/scripts/rosSimulationScalabilityWrapper.sh
Labels: analyzer, API

#912 Bump remote monitoring version to 0.0.18_rm
  manifests/crc/BYODB-installation/minikube/kruize-crc-minikube.yaml
  manifests/crc/BYODB-installation/openshift/kruize-crc-openshift.yaml
  manifests/crc/default-db-included-installation/minikube/kruize-crc-minikube.yaml
  manifests/crc/default-db-included-installation/openshift/kruize-crc-openshift.yaml
Labels: release

#914 Error map for updateResults
  src/main/java/com/autotune/analyzer/experiment/ExperimentInitiator.java
  src/main/java/com/autotune/analyzer/serviceObjects/UpdateResultsAPIObject.java
  src/main/java/com/autotune/analyzer/utils/AnalyzerErrorConstants.java
  src/main/java/com/autotune/database/dao/ExperimentDAOImpl.java
  src/main/java/com/autotune/database/helper/DBHelpers.java
  tests/scripts/remote_monitoring_tests/rest_apis/test_update_results.py
Labels: API

#854 added updaterecommendation API details into MD file
  design/MonitoringModeAPI.md
Labels: analyzer, API
