Repository kruize/autotune, pull requests merged in 2023-11, with the labels that each got.

#965 Suppress Error messages
  src/main/java/com/autotune/database/dao/ExperimentDAOImpl.java
Labels: code_cleanup/refactor

#814 Add validation for Update Results API Params
  src/main/java/com/autotune/analyzer/experiment/ExperimentInitiator.java
  src/main/java/com/autotune/analyzer/performanceProfiles/utils/PerformanceProfileUtil.java
  src/main/java/com/autotune/analyzer/serviceObjects/Converters.java
  src/main/java/com/autotune/analyzer/serviceObjects/UpdateResultsAPIObject.java
  src/main/java/com/autotune/analyzer/serviceObjects/verification/validators/KubernetesElementsValidator.java
  src/main/java/com/autotune/analyzer/serviceObjects/verification/validators/PerformanceProfileValidator.java
  src/main/java/com/autotune/analyzer/utils/AnalyzerErrorConstants.java
  src/main/java/com/autotune/utils/KruizeSupportedTypes.java
Labels: bug

#1018 Bump mvp_demo branch to 0.0.20_mvp
  manifests/crc/BYODB-installation/minikube/kruize-crc-minikube.yaml
  manifests/crc/BYODB-installation/openshift/kruize-crc-openshift.yaml
  manifests/crc/default-db-included-installation/minikube/kruize-crc-minikube.yaml
  manifests/crc/default-db-included-installation/openshift/kruize-crc-openshift.yaml
  pom.xml
Labels: release

#967 Script to gather Kruize metrics
  scripts/kruize_metrics.py
Labels: remote_monitoring

#1023 Make CPU Limits to point correctly, earlier it's pointing to cpu request
  src/main/java/com/autotune/analyzer/recommendations/engine/CostRecommendationEngine.java
  src/main/java/com/autotune/analyzer/recommendations/engine/PerformanceRecommendationEngine.java
Labels: priority, recommendation

#1024 Update kruize metrics document
  design/KruizePromQL.md
Labels: documentation, remote_monitoring, recommendation_algorithm

#981 Add and update tests for the listRecommendations and UpdateRecommendations APIs
  design/MonitoringModeAPI.md
  tests/scripts/remote_monitoring_tests/helpers/long_term_list_reco_json_schema.py
  tests/scripts/remote_monitoring_tests/helpers/medium_term_list_reco_json_schema.py
  tests/scripts/remote_monitoring_tests/helpers/utils.py
  tests/scripts/remote_monitoring_tests/rest_apis/test_e2e_workflow.py
  tests/scripts/remote_monitoring_tests/rest_apis/test_list_recommendations.py
  tests/scripts/remote_monitoring_tests/rest_apis/test_update_recommendations.py
Labels: test

#1029 Merge 0.0.20_rm changes from mvp_demo to master
  design/KruizePromQL.md
  design/MonitoringModeAPI.md
  manifests/crc/default-db-included-installation/minikube/kruize-crc-minikube.yaml
  manifests/crc/default-db-included-installation/openshift/kruize-crc-openshift.yaml
  scripts/kruize_metrics.py
  tests/scripts/remote_monitoring_tests/helpers/long_term_list_reco_json_schema.py
  tests/scripts/remote_monitoring_tests/helpers/medium_term_list_reco_json_schema.py
  tests/scripts/remote_monitoring_tests/helpers/utils.py
  tests/scripts/remote_monitoring_tests/rest_apis/test_e2e_workflow.py
  tests/scripts/remote_monitoring_tests/rest_apis/test_list_recommendations.py
  tests/scripts/remote_monitoring_tests/rest_apis/test_update_recommendations.py
Labels: release

#1038 Added support for additional units for the metric values
  src/main/java/com/autotune/analyzer/performanceProfiles/utils/PerformanceProfileUtil.java
  src/main/java/com/autotune/utils/KruizeSupportedTypes.java
Labels: enhancement, remote_monitoring

#1044 Bump mvp_demo branch to Kruize version 0.0.20.1_mvp
  manifests/crc/BYODB-installation/minikube/kruize-crc-minikube.yaml
  manifests/crc/BYODB-installation/openshift/kruize-crc-openshift.yaml
  manifests/crc/default-db-included-installation/minikube/kruize-crc-minikube.yaml
  manifests/crc/default-db-included-installation/openshift/kruize-crc-openshift.yaml
  pom.xml
Labels: release

#1045 Merge release 0.0.20.1_rm changes to master
  manifests/crc/BYODB-installation/minikube/kruize-crc-minikube.yaml
  manifests/crc/BYODB-installation/openshift/kruize-crc-openshift.yaml
  manifests/crc/default-db-included-installation/minikube/kruize-crc-minikube.yaml
  manifests/crc/default-db-included-installation/openshift/kruize-crc-openshift.yaml
  pom.xml
  scripts/kruize_metrics.py
  src/main/java/com/autotune/analyzer/performanceProfiles/utils/PerformanceProfileUtil.java
  src/main/java/com/autotune/utils/KruizeSupportedTypes.java
  tests/scripts/remote_monitoring_tests/helpers/utils.py
  tests/scripts/remote_monitoring_tests/rest_apis/test_list_recommendations.py
  tests/scripts/remote_monitoring_tests/rest_apis/test_update_results.py
Labels: release

#1046 Bump Kruize v19 to 0.0.19.5
  manifests/crc/BYODB-installation/minikube/kruize-crc-minikube.yaml
  manifests/crc/BYODB-installation/openshift/kruize-crc-openshift.yaml
  manifests/crc/default-db-included-installation/minikube/kruize-crc-minikube.yaml
  manifests/crc/default-db-included-installation/openshift/kruize-crc-openshift.yaml
  pom.xml
Labels: release

#1049 Update docs: Remove threshold related docs
  design/MonitoringModeAPI.md
Labels: documentation, remote_monitoring

#1051 Fix UpdateResultsAPI duplicate record issue
  src/main/java/com/autotune/database/dao/ExperimentDAOImpl.java
  tests/scripts/remote_monitoring_tests/fault_tolerant_tests/kruize_pod_restart_test.py
  tests/scripts/remote_monitoring_tests/helpers/kruize.py
  tests/scripts/remote_monitoring_tests/helpers/utils.py
  tests/scripts/remote_monitoring_tests/json_files/multiple_duplicate_results_single_exp.json
  tests/scripts/remote_monitoring_tests/rest_apis/test_update_results.py
Labels: bug
