Repository kruize/autotune, pull requests merged in 2023-07, with the labels that each got.

#876 add index to recommendations and results table
  design/KruizeDatabaseDesign.md
  src/main/java/com/autotune/database/table/KruizeRecommendationEntry.java
  src/main/java/com/autotune/database/table/KruizeResultsEntry.java
Labels: database

#877 DB: Add version for results and recommendations tables
  design/KruizeDatabaseDesign.md
  design/MonitoringModeAPI.md
  src/main/java/com/autotune/analyzer/recommendations/ContainerRecommendations.java
  src/main/java/com/autotune/analyzer/serviceObjects/Converters.java
  src/main/java/com/autotune/common/data/result/ExperimentResultData.java
  src/main/java/com/autotune/database/helper/DBHelpers.java
  src/main/java/com/autotune/database/table/KruizeRecommendationEntry.java
  src/main/java/com/autotune/database/table/KruizeResultsEntry.java
  src/main/java/com/autotune/utils/KruizeConstants.java
  tests/scripts/remote_monitoring_tests/helpers/list_reco_json_schema.py
Labels: database

#878 Bump version to 0.0.17_mvp
  pom.xml
Labels: release

#879 docs: fix small nitpick related to notifications type
  design/MonitoringModeAPI.md
Labels: documentation

#880 Bump remote_monitoring to 0.0.17_rm
  manifests/crc/BYODB-installation/minikube/kruize-crc-minikube.yaml
  manifests/crc/BYODB-installation/openshift/kruize-crc-openshift.yaml
  manifests/crc/default-db-included-installation/minikube/kruize-crc-minikube.yaml
  manifests/crc/default-db-included-installation/openshift/kruize-crc-openshift.yaml
Labels: release
