Repository kruize/autotune, pull requests merged in 2023-06, with the labels that each got.

#811 Fix recommendation issue: CPU Recommendation cannot be zero or negative. Test Changes Included
  design/MonitoringModeAPI.md
  design/NotificationCodes.md
  src/main/java/com/autotune/analyzer/performanceProfiles/PerformanceProfileInterface/ResourceOptimizationOpenshiftImpl.java
  src/main/java/com/autotune/analyzer/recommendations/ContainerRecommendations.java
  src/main/java/com/autotune/analyzer/recommendations/GenerateRecommendation.java
  src/main/java/com/autotune/analyzer/recommendations/Recommendation.java
  src/main/java/com/autotune/analyzer/recommendations/RecommendationNotification.java
  src/main/java/com/autotune/analyzer/recommendations/engine/DurationBasedRecommendationEngine.java
  src/main/java/com/autotune/analyzer/utils/AnalyzerConstants.java
  src/main/java/com/autotune/common/utils/CommonUtils.java
  src/main/java/com/autotune/database/helper/DBHelpers.java
  tests/scripts/remote_monitoring_tests/helpers/list_reco_json_schema.py
Labels: recommendation, API

#840 Fix notification schema
  design/MonitoringModeAPI.md
  tests/scripts/remote_monitoring_tests/helpers/utils.py
Labels: documentation, test

#838 Merge mvp_demo to master
  design/CreateExperiment.md
  design/MonitoringModeAPI.md
  design/NotificationCodes.md
  manifests/autotune/performance-profiles/resource_optimization_local_monitoring.yaml
  pom.xml
  src/main/java/com/autotune/analyzer/experiment/ExperimentInitiator.java
  src/main/java/com/autotune/analyzer/experiment/ExperimentResultValidation.java
  src/main/java/com/autotune/analyzer/experiment/ExperimentValidation.java
  src/main/java/com/autotune/analyzer/experiment/Experimentator.java
  src/main/java/com/autotune/analyzer/kruizeObject/ExperimentUseCaseType.java
  src/main/java/com/autotune/analyzer/kruizeObject/KruizeObject.java
  src/main/java/com/autotune/analyzer/performanceProfiles/PerformanceProfileInterface/ResourceOptimizationOpenshiftImpl.java
  src/main/java/com/autotune/analyzer/recommendations/ContainerRecommendations.java
  src/main/java/com/autotune/analyzer/recommendations/GenerateRecommendation.java
  src/main/java/com/autotune/analyzer/recommendations/Recommendation.java
  src/main/java/com/autotune/analyzer/recommendations/RecommendationNotification.java
  src/main/java/com/autotune/analyzer/recommendations/engine/DurationBasedRecommendationEngine.java
  src/main/java/com/autotune/analyzer/serviceObjects/Converters.java
  src/main/java/com/autotune/analyzer/services/CreateExperiment.java
  src/main/java/com/autotune/analyzer/services/ListExperiments.java
  src/main/java/com/autotune/analyzer/utils/AnalyzerConstants.java
  src/main/java/com/autotune/analyzer/utils/AnalyzerErrorConstants.java
  src/main/java/com/autotune/analyzer/utils/ServiceHelpers.java
  src/main/java/com/autotune/analyzer/workerimpl/CreateExperimentManager.java
  src/main/java/com/autotune/analyzer/workerimpl/UpdateResultManager.java
  src/main/java/com/autotune/common/data/metrics/MetricResults.java
  src/main/java/com/autotune/common/data/result/IntervalResults.java
  src/main/java/com/autotune/common/utils/CommonUtils.java
  src/main/java/com/autotune/database/helper/DBHelpers.java
  src/main/java/com/autotune/database/service/ExperimentDBService.java
  src/main/java/com/autotune/operator/KruizeOperator.java
  src/main/java/com/autotune/utils/KruizeSupportedTypes.java
  tests/README.md
  tests/scripts/common/common_functions.sh
  tests/scripts/remote_monitoring_tests/helpers/list_reco_json_schema.py
  tests/scripts/remote_monitoring_tests/helpers/list_reco_json_validate.py
  tests/scripts/remote_monitoring_tests/helpers/utils.py
  tests/scripts/remote_monitoring_tests/remote_monitoring_tests.sh
  tests/scripts/remote_monitoring_tests/rest_apis/test_e2e_workflow.py
  tests/scripts/remote_monitoring_tests/rest_apis/test_list_recommendations.py
  tests/scripts/remote_monitoring_tests/rest_apis/test_update_results.py
  tests/test_autotune.sh
Labels: release

#847 Fix empty exp name acceptance in update results
  src/main/java/com/autotune/analyzer/experiment/ExperimentResultValidation.java
Labels: bug

#848 Merge mvp_demo to master
  src/main/java/com/autotune/analyzer/experiment/ExperimentResultValidation.java
  src/main/java/com/autotune/analyzer/recommendations/engine/DurationBasedRecommendationEngine.java
  tests/scripts/remote_monitoring_tests/helpers/utils.py
Labels: release

#859 Adds current config in Recommendations
  src/main/java/com/autotune/analyzer/recommendations/Recommendation.java
  src/main/java/com/autotune/analyzer/recommendations/RecommendationConfigItem.java
  src/main/java/com/autotune/analyzer/recommendations/engine/DurationBasedRecommendationEngine.java
  src/main/java/com/autotune/analyzer/recommendations/engine/KruizeRecommendationEngine.java
  src/main/java/com/autotune/analyzer/recommendations/engine/ProfileBasedRecommendationEngine.java
  src/main/java/com/autotune/analyzer/utils/AnalyzerConstants.java
  src/main/java/com/autotune/utils/KruizeConstants.java
  tests/scripts/remote_monitoring_tests/helpers/list_reco_json_schema.py
  tests/scripts/remote_monitoring_tests/helpers/utils.py
  tests/scripts/remote_monitoring_tests/rest_apis/test_e2e_workflow.py
  tests/scripts/remote_monitoring_tests/rest_apis/test_list_recommendations.py
Labels: remote_monitoring

#864 Update variation
  src/main/java/com/autotune/analyzer/recommendations/engine/DurationBasedRecommendationEngine.java
Labels: remote_monitoring

#866 Bump mvp_demo to version 0.0.16_mvp
  pom.xml
Labels: release

#860 Add Sample API responses for each notififcation
  design/APISamples.md
  design/NotificationCodes.md
  src/main/java/com/autotune/analyzer/utils/AnalyzerConstants.java
Labels: remote_monitoring

#870 Update Maven version to 3.9.3
  Dockerfile.autotune
Labels: bug

#871 merge mvp_demo to master
  .github/workflows/rm_release_test.yaml
  Dockerfile.autotune
  design/APISamples.md
  design/MonitoringModeAPI.md
  design/NotificationCodes.md
  manifests/crc/BYODB-installation/minikube/kruize-crc-minikube.yaml
  manifests/crc/BYODB-installation/openshift/kruize-crc-openshift.yaml
  manifests/crc/default-db-included-installation/minikube/kruize-crc-minikube.yaml
  manifests/crc/default-db-included-installation/openshift/kruize-crc-openshift.yaml
  pom.xml
  src/main/java/com/autotune/analyzer/recommendations/Recommendation.java
  src/main/java/com/autotune/analyzer/recommendations/RecommendationConfigItem.java
  src/main/java/com/autotune/analyzer/recommendations/engine/DurationBasedRecommendationEngine.java
  src/main/java/com/autotune/analyzer/recommendations/engine/KruizeRecommendationEngine.java
  src/main/java/com/autotune/analyzer/recommendations/engine/ProfileBasedRecommendationEngine.java
  src/main/java/com/autotune/analyzer/utils/AnalyzerConstants.java
  src/main/java/com/autotune/utils/KruizeConstants.java
  tests/README.md
  tests/scripts/common/common_functions.sh
  tests/scripts/remote_monitoring_tests/README.md
  tests/scripts/remote_monitoring_tests/fault_tolerant_tests.md
  tests/scripts/remote_monitoring_tests/fault_tolerant_tests/kruize_pod_restart_test.py
  tests/scripts/remote_monitoring_tests/fault_tolerant_tests/remote_monitoring_fault_tolerant_tests.sh
  tests/scripts/remote_monitoring_tests/helpers/generate_rm_jsons.py
  tests/scripts/remote_monitoring_tests/helpers/kruize.py
  tests/scripts/remote_monitoring_tests/helpers/list_reco_json_schema.py
  tests/scripts/remote_monitoring_tests/helpers/utils.py
  tests/scripts/remote_monitoring_tests/rest_apis/test_e2e_workflow.py
  tests/scripts/remote_monitoring_tests/rest_apis/test_list_recommendations.py
  tests/scripts/remote_monitoring_tests/stress_test/jmx/kruize_remote_monitoring_stress.jmx
  tests/scripts/remote_monitoring_tests/stress_test/jmx/kruize_remote_monitoring_stress_openshift.jmx
  tests/scripts/remote_monitoring_tests/stress_test/monitor-metrics-promql.sh
  tests/scripts/remote_monitoring_tests/stress_test/remote_monitoring_stress_test.sh
Labels: release
