Repository kruize/autotune, pull requests merged in 2024-03, with the labels that each got.

#1111 Add Database tables for Datasource and metadata
  migrations/kruize_experiments_ddl.sql
  src/main/java/com/autotune/Autotune.java
  src/main/java/com/autotune/analyzer/serviceObjects/CreateExperimentAPIObject.java
  src/main/java/com/autotune/common/datasource/DataSourceCollection.java
  src/main/java/com/autotune/common/datasource/DataSourceInfo.java
  src/main/java/com/autotune/common/datasource/DataSourceManager.java
  src/main/java/com/autotune/database/dao/ExperimentDAO.java
  src/main/java/com/autotune/database/dao/ExperimentDAOImpl.java
  src/main/java/com/autotune/database/helper/DBConstants.java
  src/main/java/com/autotune/database/helper/DBHelpers.java
  src/main/java/com/autotune/database/init/KruizeHibernateUtil.java
  src/main/java/com/autotune/database/service/ExperimentDBService.java
  src/main/java/com/autotune/database/table/KruizeDataSource.java
  src/main/java/com/autotune/database/table/KruizeExperimentEntry.java
  src/main/java/com/autotune/database/table/KruizeMetadata.java
  src/main/java/com/autotune/operator/InitializeDeployment.java
Labels: kruize-local

#1096 Document updates for the term threshold changes
  design/MonitoringModeAPI.md
  design/TermThresholdDesign.md
Labels: documentation

#1124 Troubleshooting EE Perfprofile error and avoid Pod restart solution.
  src/main/java/com/autotune/Autotune.java
  src/main/java/com/autotune/database/init/KruizeHibernateUtil.java
Labels: bug

#1105 Refactor recommendation code
  src/main/java/com/autotune/analyzer/experiment/ExperimentInitiator.java
  src/main/java/com/autotune/analyzer/kruizeObject/KruizeObject.java
  src/main/java/com/autotune/analyzer/performanceProfiles/PerformanceProfile.java
  src/main/java/com/autotune/analyzer/performanceProfiles/PerformanceProfileInterface/DefaultImpl.java
  src/main/java/com/autotune/analyzer/performanceProfiles/PerformanceProfileInterface/PerfProfileImpl.java
  src/main/java/com/autotune/analyzer/performanceProfiles/PerformanceProfileInterface/PerfProfileInterface.java
  src/main/java/com/autotune/analyzer/performanceProfiles/PerformanceProfileInterface/ResourceOptimizationOpenshiftImpl.java
  src/main/java/com/autotune/analyzer/recommendations/GenerateRecommendation.java
  src/main/java/com/autotune/analyzer/recommendations/RecommendationConstants.java
  src/main/java/com/autotune/analyzer/recommendations/RecommendationNotification.java
  src/main/java/com/autotune/analyzer/recommendations/engine/KruizeRecommendationEngine.java
  src/main/java/com/autotune/analyzer/recommendations/engine/PerformanceRecommendationEngine.java
  src/main/java/com/autotune/analyzer/recommendations/engine/RecommendationEngine.java
  src/main/java/com/autotune/analyzer/recommendations/model/CostBasedRecommendationModel.java
  src/main/java/com/autotune/analyzer/recommendations/model/PerformanceBasedRecommendationModel.java
  src/main/java/com/autotune/analyzer/recommendations/model/RecommendationModel.java
  src/main/java/com/autotune/analyzer/recommendations/objects/MappedRecommendationForModel.java
  src/main/java/com/autotune/analyzer/recommendations/objects/MappedRecommendationForTerm.java
  src/main/java/com/autotune/analyzer/recommendations/objects/TermRecommendations.java
  src/main/java/com/autotune/analyzer/recommendations/subCategory/CostRecommendationSubCategory.java
  src/main/java/com/autotune/analyzer/recommendations/subCategory/PerformanceRecommendationSubCategory.java
  src/main/java/com/autotune/analyzer/recommendations/subCategory/RecommendationSubCategory.java
  src/main/java/com/autotune/analyzer/recommendations/term/Terms.java
  src/main/java/com/autotune/analyzer/recommendations/utils/RecommendationUtils.java
  src/main/java/com/autotune/analyzer/services/UpdateRecommendations.java
  src/main/java/com/autotune/analyzer/utils/AnalyzerConstants.java
  src/main/java/com/autotune/database/helper/DBHelpers.java
  src/main/java/com/autotune/database/service/ExperimentDBService.java
  src/main/java/com/autotune/utils/KruizeConstants.java
  tests/scripts/remote_monitoring_tests/rest_apis/test_list_recommendations.py
  tests/scripts/remote_monitoring_tests/rest_apis/test_update_recommendations.py
Labels: remote_monitoring, recommendation, code_cleanup/refactor

#1126 Enhance datasource info retrieval from DB with service name validation
  src/main/java/com/autotune/database/helper/DBHelpers.java
Labels: kruize-local

#1130 Box Plots Preview Code
  design/MonitoringModeAPI.md
  manifests/crc/default-db-included-installation/minikube/kruize-crc-minikube.yaml
  manifests/crc/default-db-included-installation/openshift/kruize-crc-openshift.yaml
  src/main/java/com/autotune/analyzer/kruizeObject/KruizeObject.java
  src/main/java/com/autotune/analyzer/plots/PlotData.java
  src/main/java/com/autotune/analyzer/plots/PlotManager.java
  src/main/java/com/autotune/analyzer/recommendations/RecommendationConstants.java
  src/main/java/com/autotune/analyzer/recommendations/engine/RecommendationEngine.java
  src/main/java/com/autotune/analyzer/recommendations/objects/TermRecommendations.java
  src/main/java/com/autotune/analyzer/recommendations/term/Terms.java
  src/main/java/com/autotune/operator/InitializeDeployment.java
  src/main/java/com/autotune/operator/KruizeDeploymentInfo.java
  src/main/java/com/autotune/utils/KruizeConstants.java
Labels: enhancement, remote_monitoring

#1141 Fix Postgres Connection Count
  src/main/java/com/autotune/Autotune.java
  src/main/java/com/autotune/database/init/KruizeHibernateUtil.java
Labels: bug

#1143 Bump mvp_demo version to 0.0.20.3_mvp
  manifests/crc/BYODB-installation/minikube/kruize-crc-minikube.yaml
  manifests/crc/BYODB-installation/openshift/kruize-crc-openshift.yaml
  manifests/crc/default-db-included-installation/minikube/kruize-crc-minikube.yaml
  manifests/crc/default-db-included-installation/openshift/kruize-crc-openshift.yaml
  pom.xml
Labels: release

#1142 Fix missing Recommendations
  src/main/java/com/autotune/analyzer/recommendations/term/Terms.java
  src/main/java/com/autotune/utils/KruizeConstants.java
Labels: bug
