Repository kruize/autotune, pull requests merged in 2024-01, with the labels that each got.

#1080 Add Datasource to Global Hashmap on Initialization
  manifests/crc/default-db-included-installation/minikube/kruize-crc-minikube.yaml
  src/main/java/com/autotune/common/datasource/DataSourceCollection.java
  src/main/java/com/autotune/common/datasource/DataSourceFactory.java
  src/main/java/com/autotune/common/datasource/DataSourceInfo.java
  src/main/java/com/autotune/common/datasource/DataSourceOperator.java
  src/main/java/com/autotune/common/datasource/DataSourceOperatorImpl.java
  src/main/java/com/autotune/common/datasource/PrometheusDataOperator.java
  src/main/java/com/autotune/common/datasource/PrometheusDataSource.java
  src/main/java/com/autotune/common/datasource/prometheus/PrometheusDataOperatorImpl.java
  src/main/java/com/autotune/common/exceptions/DataSourceAlreadyExist.java
  src/main/java/com/autotune/common/exceptions/DataSourceMissingRequiredFiled.java
  src/main/java/com/autotune/common/exceptions/DataSourceNotExist.java
  src/main/java/com/autotune/common/exceptions/DataSourceNotServiceable.java
  src/main/java/com/autotune/common/exceptions/ServiceNotFound.java
  src/main/java/com/autotune/common/exceptions/UnsupportedDataSourceProvider.java
  src/main/java/com/autotune/experimentManager/handler/MetricCollectionHandler.java
  src/main/java/com/autotune/operator/InitializeDeployment.java
  src/main/java/com/autotune/utils/KruizeConstants.java
  src/main/java/com/autotune/utils/TrialHelpers.java
Labels: kruize-local

#1002 docs : update test_list_recommendations file path
  tests/scripts/remote_monitoring_tests/Remote_monitoring_tests.md
Labels: documentation

#1084 delete Partitions RM to MVP
  design/KruizeConfiguration.md
  manifests/crc/default-db-included-installation/minikube/kruize-crc-minikube.yaml
  manifests/crc/default-db-included-installation/openshift/kruize-crc-openshift.yaml
  pom.xml
  src/main/java/com/autotune/database/dao/ExperimentDAO.java
  src/main/java/com/autotune/database/dao/ExperimentDAOImpl.java
  src/main/java/com/autotune/database/helper/DBConstants.java
  src/main/java/com/autotune/jobs/RetentionPartition.java
  src/main/java/com/autotune/operator/KruizeDeploymentInfo.java
  src/main/java/com/autotune/utils/KruizeConstants.java
Labels: remote_monitoring

#1030 Fix the NPE issue in ListExperimentsAPI
  src/main/java/com/autotune/analyzer/serviceObjects/Converters.java
  src/main/java/com/autotune/analyzer/services/ListExperiments.java
  src/main/java/com/autotune/database/service/ExperimentDBService.java
  tests/scripts/remote_monitoring_tests/fault_tolerant_tests/remote_monitoring_fault_tolerant_tests.sh
Labels: bug

#1085 Handle null after space increase
  src/main/java/com/autotune/database/helper/DBHelpers.java
Labels: remote_monitoring

#1086 Refactor datasource package classes
  src/main/java/com/autotune/common/datasource/DataSource.java
  src/main/java/com/autotune/common/datasource/DataSourceFactory.java
  src/main/java/com/autotune/common/datasource/DataSourceOperator.java
  src/main/java/com/autotune/common/datasource/DataSourceOperatorImpl.java
  src/main/java/com/autotune/common/datasource/KruizeDataSource.java
  src/main/java/com/autotune/common/datasource/KruizeDataSourceCollection.java
  src/main/java/com/autotune/common/datasource/KruizeDataSourceOperator.java
  src/main/java/com/autotune/common/datasource/KruizeDataSourceServiceability.java
  src/main/java/com/autotune/common/datasource/PrometheusDataSource.java
  src/main/java/com/autotune/common/datasource/prometheus/PrometheusDataOperatorImpl.java
  src/main/java/com/autotune/experimentManager/handler/MetricCollectionHandler.java
  src/main/java/com/autotune/operator/InitializeDeployment.java
  src/main/java/com/autotune/operator/KruizeOperator.java
  tests/scripts/da/constants/configmap_constants.sh
Labels: kruize-local
