Repository kruize/autotune, pull requests merged in 2024-10, with the labels that each got.

#896 Add the missing steps in the autotune_installation
  docs/autotune_install.md
Labels: documentation

#1313 Adds GPU queries to performance profile
  manifests/autotune/performance-profiles/resource_optimization_local_monitoring.json
  manifests/autotune/performance-profiles/resource_optimization_local_monitoring.yaml
  manifests/autotune/performance-profiles/resource_optimization_local_monitoring_norecordingrules.json
  manifests/autotune/performance-profiles/resource_optimization_local_monitoring_norecordingrules.yaml
Labels: remote_monitoring

#1314 Add Accelerator specific interfaces and there respective implementations
  src/main/java/com/autotune/analyzer/utils/AnalyzerConstants.java
  src/main/java/com/autotune/common/data/system/info/device/ContainerDeviceList.java
  src/main/java/com/autotune/common/data/system/info/device/DeviceComponentDetector.java
  src/main/java/com/autotune/common/data/system/info/device/DeviceDetails.java
  src/main/java/com/autotune/common/data/system/info/device/DeviceHandler.java
  src/main/java/com/autotune/common/data/system/info/device/accelerator/AcceleratorDeviceData.java
  src/main/java/com/autotune/common/data/system/info/device/accelerator/AcceleratorDeviceDetails.java
  src/main/java/com/autotune/common/data/system/info/device/accelerator/metadata/AcceleratorMetaDataService.java
  src/main/java/com/autotune/common/data/system/info/device/accelerator/metadata/AcceleratorProfile.java
Labels: remote_monitoring

#1323 1. Bulk documentation
  design/BulkAPI.md
Labels: API

#1328 3. bulk service
  src/main/java/com/autotune/analyzer/services/BulkService.java
Labels: API

#1329 4. bulk job manager
  src/main/java/com/autotune/analyzer/kruizeObject/CreateExperimentConfigBean.java
  src/main/java/com/autotune/analyzer/serviceObjects/KubernetesAPIObject.java
  src/main/java/com/autotune/analyzer/services/BulkService.java
  src/main/java/com/autotune/analyzer/workerimpl/BulkJobManager.java
  src/main/java/com/autotune/operator/KruizeDeploymentInfo.java
  src/main/java/com/autotune/utils/KruizeConstants.java
Labels: API

#1330 5. bulk meta data change
  src/main/java/com/autotune/analyzer/services/DSMetadataService.java
  src/main/java/com/autotune/analyzer/workerimpl/BulkJobManager.java
  src/main/java/com/autotune/common/data/dataSourceQueries/DataSourceQueries.java
  src/main/java/com/autotune/common/datasource/DataSourceManager.java
  src/main/java/com/autotune/common/datasource/DataSourceMetadataOperator.java
  src/main/java/com/autotune/database/dao/ExperimentDAOImpl.java
  src/main/java/com/autotune/database/service/ExperimentDBService.java
Labels: API

#1309 Exclude namespace queries to fetch container metric data
  src/main/java/com/autotune/analyzer/recommendations/engine/RecommendationEngine.java
Labels: bug, kruize-local

#1335 Add recommendation URLs in the manifest for bulk API
  manifests/crc/BYODB-installation/minikube/kruize-crc-minikube.yaml
  manifests/crc/BYODB-installation/openshift/kruize-crc-openshift.yaml
  manifests/crc/default-db-included-installation/aks/kruize-crc-aks.yaml
  manifests/crc/default-db-included-installation/minikube/kruize-crc-minikube.yaml
  manifests/crc/default-db-included-installation/openshift/kruize-crc-openshift.yaml
Labels: enhancement

#1253 Fixing numpods cant be zero error
  src/main/java/com/autotune/analyzer/recommendations/engine/RecommendationEngine.java
Labels: remote_monitoring

#1337 Refactor Bulk Job Manager to call createExperiments API
  manifests/crc/BYODB-installation/minikube/kruize-crc-minikube.yaml
  manifests/crc/BYODB-installation/openshift/kruize-crc-openshift.yaml
  manifests/crc/default-db-included-installation/aks/kruize-crc-aks.yaml
  manifests/crc/default-db-included-installation/minikube/kruize-crc-minikube.yaml
  manifests/crc/default-db-included-installation/openshift/kruize-crc-openshift.yaml
  src/main/java/com/autotune/analyzer/kruizeObject/CreateExperimentConfigBean.java
  src/main/java/com/autotune/analyzer/recommendations/engine/RecommendationEngine.java
  src/main/java/com/autotune/analyzer/serviceObjects/BulkJobStatus.java
  src/main/java/com/autotune/analyzer/services/BulkService.java
  src/main/java/com/autotune/analyzer/workerimpl/BulkJobManager.java
  src/main/java/com/autotune/common/datasource/DataSourceMetadataOperator.java
  src/main/java/com/autotune/operator/KruizeDeploymentInfo.java
  src/main/java/com/autotune/utils/GenericRestApiClient.java
  src/main/java/com/autotune/utils/KruizeConstants.java
Labels: bug, remote_monitoring, code_cleanup/refactor

#1336 Add tests for validating recommendation json for accelerator values
  tests/scripts/helpers/utils.py
  tests/scripts/local_monitoring_tests/Local_monitoring_tests.md
  tests/scripts/local_monitoring_tests/rest_apis/test_list_recommendations.py
Labels: remote_monitoring

#1334 set kruize local to true
  manifests/crc/BYODB-installation/minikube/kruize-crc-minikube.yaml
  manifests/crc/BYODB-installation/openshift/kruize-crc-openshift.yaml
  manifests/crc/default-db-included-installation/aks/kruize-crc-aks.yaml
  manifests/crc/default-db-included-installation/minikube/kruize-crc-minikube.yaml
  manifests/crc/default-db-included-installation/openshift/kruize-crc-openshift.yaml
  src/main/java/com/autotune/operator/KruizeDeploymentInfo.java
  tests/scripts/common/common_functions.sh
  tests/scripts/remote_monitoring_tests/fault_tolerant_tests/remote_monitoring_fault_tolerant_tests.sh
  tests/scripts/remote_monitoring_tests/remote_monitoring_tests.sh
  tests/scripts/remote_monitoring_tests/scale_test/remote_monitoring_scale_test.sh
  tests/scripts/remote_monitoring_tests/scale_test/remote_monitoring_scale_test_bulk.sh
  tests/scripts/remote_monitoring_tests/stress_test/remote_monitoring_stress_test.sh
Labels: API

#1322 Update datasource metadata queries
  src/main/java/com/autotune/common/data/dataSourceQueries/DataSourceQueries.java
  src/main/java/com/autotune/database/helper/DBHelpers.java
  tests/scripts/helpers/list_metadata_json_verbose_true_schema.py
Labels: bug, local_monitoring

#1333 Bump mvp_demo to Kruize version 0.1!
  manifests/crc/BYODB-installation/minikube/kruize-crc-minikube.yaml
  manifests/crc/BYODB-installation/openshift/kruize-crc-openshift.yaml
  manifests/crc/default-db-included-installation/aks/kruize-crc-aks.yaml
  manifests/crc/default-db-included-installation/minikube/kruize-crc-minikube.yaml
  manifests/crc/default-db-included-installation/openshift/kruize-crc-openshift.yaml
  pom.xml
Labels: release

#1354 Resolve issue where error is not being returned to the caller.
  src/main/java/com/autotune/common/datasource/DataSourceManager.java
  src/main/java/com/autotune/common/datasource/DataSourceMetadataOperator.java
  src/main/java/com/autotune/common/datasource/prometheus/PrometheusDataOperatorImpl.java
Labels: bug

#1353 422 error found duplicate series for the match group
  src/main/java/com/autotune/common/data/dataSourceQueries/DataSourceQueries.java
Labels: bug

#1355 Bump mvp_demo to Kruize Version 0.1.1
  manifests/crc/BYODB-installation/minikube/kruize-crc-minikube.yaml
  manifests/crc/BYODB-installation/openshift/kruize-crc-openshift.yaml
  manifests/crc/default-db-included-installation/aks/kruize-crc-aks.yaml
  manifests/crc/default-db-included-installation/minikube/kruize-crc-minikube.yaml
  manifests/crc/default-db-included-installation/openshift/kruize-crc-openshift.yaml
  pom.xml
Labels: release
