Repository kruize/autotune, pull requests merged in 2024-12, with the labels that each got.

#1403 Update kruize-ui to v0.0.8
  manifests/crc/BYODB-installation/minikube/kruize-crc-minikube.yaml
  manifests/crc/BYODB-installation/openshift/kruize-crc-openshift.yaml
  manifests/crc/default-db-included-installation/aks/kruize-crc-aks.yaml
  manifests/crc/default-db-included-installation/minikube/kruize-crc-minikube.yaml
  manifests/crc/default-db-included-installation/openshift/kruize-crc-openshift.yaml
Labels: release

#1407 Upgrade Jetty Server version to resolve the CVE-2024-6763 Issue
  pom.xml
  src/main/java/com/autotune/Autotune.java
  src/main/java/com/autotune/analyzer/Analyzer.java
  src/main/java/com/autotune/analyzer/exceptions/KruizeErrorHandler.java
  src/main/java/com/autotune/experimentManager/core/ExperimentManager.java
  src/main/java/com/autotune/utils/filter/KruizeCORSFilter.java
Labels: dependencies

#1411 2. Update Fabric8 Version to 7.0.0 and Add VerticalPodScaler Client [KRUIZE-VPA Integration]
  pom.xml
  src/main/java/com/autotune/analyzer/performanceProfiles/PerformanceProfilesDeployment.java
  src/main/java/com/autotune/common/target/kubernetes/service/impl/KubernetesServicesImpl.java
  src/main/java/com/autotune/experimentManager/transitions/TransitionToCreateConfig.java
  src/main/java/com/autotune/operator/KruizeOperator.java
Labels: remote_monitoring

#1410 1. Updating Manifests to Include Cluster Roles and RoleBindings for VPA Object Management [KRUIZE-VPA Integration]
  manifests/crc/default-db-included-installation/minikube/kruize-crc-minikube.yaml
  manifests/crc/default-db-included-installation/openshift/kruize-crc-openshift.yaml
Labels: remote_monitoring

#1418 Fixing "No Data Available" in GenerateRecommendations API
  src/main/java/com/autotune/analyzer/recommendations/engine/RecommendationEngine.java
Labels: remote_monitoring

#1412 3. Adding Recommendation Updater Abstraction and VPA Updater [KRUIZE-VPA Integration]
  src/main/java/com/autotune/analyzer/exceptions/ApplyRecommendationsError.java
  src/main/java/com/autotune/analyzer/exceptions/InvalidRecommendationUpdaterType.java
  src/main/java/com/autotune/analyzer/exceptions/UnableToCreateVPAException.java
  src/main/java/com/autotune/analyzer/recommendations/updater/RecommendationUpdater.java
  src/main/java/com/autotune/analyzer/recommendations/updater/RecommendationUpdaterImpl.java
  src/main/java/com/autotune/analyzer/recommendations/updater/vpa/VpaUpdaterImpl.java
  src/main/java/com/autotune/analyzer/recommendations/utils/RecommendationUtils.java
  src/main/java/com/autotune/analyzer/utils/AnalyzerConstants.java
  src/main/java/com/autotune/analyzer/utils/AnalyzerErrorConstants.java
Labels: remote_monitoring

#1415 4. Adding Support For VPA and Auto Mode in CreateExperiment [KRUIZE-VPA Integration]
  src/main/java/com/autotune/analyzer/kruizeObject/ExperimentUseCaseType.java
  src/main/java/com/autotune/analyzer/utils/AnalyzerConstants.java
Labels: remote_monitoring

#1422 Removing Redundant SSL Verification Related Functions
  src/main/java/com/autotune/utils/HttpUtils.java
Labels: remote_monitoring

#1400 Fix issues with the Bulk API Scale Tests
  src/main/java/com/autotune/database/dao/ExperimentDAOImpl.java
Labels: bug

#1416 5. Adding Recommendation Updater Service [KRUIZE-VPA Integration]
  src/main/java/com/autotune/Autotune.java
  src/main/java/com/autotune/analyzer/kruizeObject/KruizeObject.java
  src/main/java/com/autotune/analyzer/recommendations/updater/RecommendationUpdaterService.java
  src/main/java/com/autotune/analyzer/utils/AnalyzerConstants.java
  src/main/java/com/autotune/analyzer/utils/AnalyzerErrorConstants.java
  src/main/java/com/autotune/database/dao/ExperimentDAO.java
  src/main/java/com/autotune/database/dao/ExperimentDAOImpl.java
  src/main/java/com/autotune/database/helper/DBConstants.java
  src/main/java/com/autotune/database/service/ExperimentDBService.java
Labels: remote_monitoring

#1391 Add filtration feature in the bulk API
  design/BulkAPI.md
  src/main/java/com/autotune/analyzer/services/DSMetadataService.java
  src/main/java/com/autotune/analyzer/workerimpl/BulkJobManager.java
  src/main/java/com/autotune/common/data/dataSourceMetadata/DataSourceMetadataHelper.java
  src/main/java/com/autotune/common/data/dataSourceQueries/DataSourceQueries.java
  src/main/java/com/autotune/common/datasource/DataSourceManager.java
  src/main/java/com/autotune/common/datasource/DataSourceMetadataOperator.java
  src/main/java/com/autotune/database/dao/ExperimentDAOImpl.java
Labels: enhancement

#1424 Functional test suit amendment to address RM and LM
  tests/scripts/local_monitoring_tests/fault_tolerant_test/kruize_pod_restart_test.py
  tests/scripts/remote_monitoring_tests/rest_apis/test_list_recommendations.py
  tests/scripts/remote_monitoring_tests/rest_apis/test_update_recommendations.py
Labels: API

#1426 Concurrent RM and LM fault tolerance fix
  tests/scripts/helpers/kruize.py
  tests/scripts/remote_monitoring_tests/fault_tolerant_tests/kruize_pod_restart_test.py
Labels: API

#1428 Fixing Namespace Experiments Not Getting Created
  src/main/java/com/autotune/analyzer/kruizeObject/KruizeObject.java
  src/main/java/com/autotune/analyzer/serviceObjects/CreateExperimentAPIObject.java
  src/main/java/com/autotune/analyzer/serviceObjects/ListRecommendationsAPIObject.java
  src/main/java/com/autotune/analyzer/utils/ExperimentTypeUtil.java
Labels: bug, remote_monitoring

#1430 Fixing ListExperiments API Not Listing Recommendations
  src/main/java/com/autotune/analyzer/serviceObjects/Converters.java
  src/main/java/com/autotune/analyzer/services/ListExperiments.java
Labels: bug, remote_monitoring

#1432 Fix issue with the DB migration test
  src/main/java/com/autotune/common/datasource/DataSourceMetadataOperator.java
  tests/scripts/remote_monitoring_tests/db_migration_test/db_migration_test.sh
  tests/scripts/remote_monitoring_tests/db_migration_test/db_migration_test_without_postgres_restart.sh
Labels: bug, test

#1436 Fix Remote Monitoring Negative Test Failure
  tests/scripts/remote_monitoring_tests/rest_apis/test_update_results.py
Labels: bug, test

#1431 Bulk demo fix
  src/main/java/com/autotune/analyzer/serviceObjects/BulkJobStatus.java
  src/main/java/com/autotune/analyzer/services/BulkService.java
  src/main/java/com/autotune/analyzer/workerimpl/BulkJobManager.java
Labels: API

#1427 Bump mvp_demo to Kruize version v0.3
  manifests/crc/BYODB-installation/minikube/kruize-crc-minikube.yaml
  manifests/crc/BYODB-installation/openshift/kruize-crc-openshift.yaml
  manifests/crc/default-db-included-installation/aks/kruize-crc-aks.yaml
  manifests/crc/default-db-included-installation/minikube/kruize-crc-minikube.yaml
  manifests/crc/default-db-included-installation/openshift/kruize-crc-openshift.yaml
  pom.xml
Labels: release

#1433 Add test plan & results for 0.3
  tests/test_plans/test_plan_rel_0.3.md
Labels: documentation, test
