Repository kruize/autotune, pull requests merged in 2024-06, with the labels that each got.

#1208 Set box plots flag as true by default
  src/main/java/com/autotune/operator/KruizeDeploymentInfo.java
Labels: bug

#1202 Clean up recommendation classes
  src/main/java/com/autotune/analyzer/recommendations/engine/RecommendationEngine.java
  src/main/java/com/autotune/analyzer/services/UpdateRecommendations.java
  src/main/java/com/autotune/analyzer/utils/AnalyzerErrorConstants.java
  src/main/java/com/autotune/utils/KruizeConstants.java
Labels: code_cleanup/refactor

#1203 Format the durationInhours value
  src/main/java/com/autotune/analyzer/recommendations/term/Terms.java
  tests/scripts/helpers/utils.py
Labels: bug

#1194 Add initContainer in Kruize pod to check PostGres pod readiness
  manifests/crc/BYODB-installation/minikube/kruize-crc-minikube.yaml
  manifests/crc/BYODB-installation/openshift/kruize-crc-openshift.yaml
  manifests/crc/default-db-included-installation/minikube/kruize-crc-minikube.yaml
  manifests/crc/default-db-included-installation/openshift/kruize-crc-openshift.yaml
  scripts/common_utils.sh
  scripts/ffdc.sh
Labels: enhancement

#1201 Log updateRecommendations failure message
  src/main/java/com/autotune/analyzer/services/UpdateRecommendations.java
  src/main/java/com/autotune/utils/KruizeConstants.java
Labels: remote_monitoring

#1199 Add testcases for GET /dsmetadata API
  tests/scripts/helpers/kruize.py
  tests/scripts/helpers/list_datasources_json_schema.py
  tests/scripts/helpers/list_metadata_json_cluster_name_without_verbose_schema.py
  tests/scripts/helpers/list_metadata_json_schema.py
  tests/scripts/helpers/list_metadata_json_validate.py
  tests/scripts/helpers/list_metadata_json_verbose_true_schema.py
  tests/scripts/helpers/utils.py
  tests/scripts/local_monitoring_tests/Local_monitoring_tests.md
  tests/scripts/local_monitoring_tests/requirements.txt
  tests/scripts/local_monitoring_tests/rest_apis/test_import_metadata.py
  tests/scripts/local_monitoring_tests/rest_apis/test_list_metadata.py
  tests/scripts/remote_monitoring_tests/requirements.txt
Labels: test, kruize-local

#1066 Documentation Update for Supported Metric Types in updateResults
  design/MonitoringModeAPI.md
Labels: documentation, remote_monitoring, kruize-local

#1200 Enhancement of list and import metadata APIs
  src/main/java/com/autotune/analyzer/serviceObjects/DSMetadataAPIObject.java
  src/main/java/com/autotune/analyzer/services/DSMetadataService.java
  src/main/java/com/autotune/analyzer/utils/AnalyzerConstants.java
  src/main/java/com/autotune/analyzer/utils/AnalyzerErrorConstants.java
  src/main/java/com/autotune/utils/MetricsConfig.java
Labels: kruize-local

#1211 Test multiple metadata import without datasource connection
  tests/scripts/helpers/utils.py
  tests/scripts/local_monitoring_tests/Local_monitoring_tests.md
  tests/scripts/local_monitoring_tests/rest_apis/test_import_metadata.py
Labels: test, kruize-local

#1215 Fix error response message for list metadata tests
  tests/scripts/helpers/utils.py
  tests/scripts/local_monitoring_tests/rest_apis/test_list_metadata.py
Labels: test, kruize-local

#1054 Included PR and issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
Labels: enhancement, remote_monitoring

#1212 Bump mvp_demo to version 0.0.23_mvp
  manifests/crc/BYODB-installation/minikube/kruize-crc-minikube.yaml
  manifests/crc/BYODB-installation/openshift/kruize-crc-openshift.yaml
  manifests/crc/default-db-included-installation/minikube/kruize-crc-minikube.yaml
  manifests/crc/default-db-included-installation/openshift/kruize-crc-openshift.yaml
  pom.xml
Labels: release

#1220 Merge mvp_demo (0.0.23_mvp) to master
  Dockerfile.autotune
  design/KruizePromQL.md
  design/MonitoringModeAPI.md
  manifests/crc/BYODB-installation/minikube/kruize-crc-minikube.yaml
  manifests/crc/BYODB-installation/openshift/kruize-crc-openshift.yaml
  manifests/crc/default-db-included-installation/minikube/kruize-crc-minikube.yaml
  manifests/crc/default-db-included-installation/openshift/kruize-crc-openshift.yaml
  pom.xml
  scripts/common_utils.sh
  scripts/ffdc.sh
  scripts/kruize_metrics.py
  src/main/java/com/autotune/analyzer/recommendations/engine/RecommendationEngine.java
  src/main/java/com/autotune/analyzer/recommendations/term/Terms.java
  src/main/java/com/autotune/analyzer/serviceObjects/DSMetadataAPIObject.java
  src/main/java/com/autotune/analyzer/services/DSMetadataService.java
  src/main/java/com/autotune/analyzer/services/UpdateRecommendations.java
  src/main/java/com/autotune/analyzer/services/UpdateResults.java
  src/main/java/com/autotune/analyzer/utils/AnalyzerConstants.java
  src/main/java/com/autotune/analyzer/utils/AnalyzerErrorConstants.java
  src/main/java/com/autotune/common/data/dataSourceQueries/DataSourceQueries.java
  src/main/java/com/autotune/common/datasource/DataSourceManager.java
  src/main/java/com/autotune/common/datasource/DataSourceMetadataOperator.java
  src/main/java/com/autotune/common/datasource/DataSourceMetadataValidation.java
  src/main/java/com/autotune/database/dao/ExperimentDAO.java
  src/main/java/com/autotune/database/dao/ExperimentDAOImpl.java
  src/main/java/com/autotune/database/helper/DBConstants.java
  src/main/java/com/autotune/metrics/KruizeNotificationCollectionRegistry.java
  src/main/java/com/autotune/operator/KruizeDeploymentInfo.java
  src/main/java/com/autotune/utils/KruizeConstants.java
  src/main/java/com/autotune/utils/MetricsConfig.java
  tests/scripts/common/common_functions.sh
  tests/scripts/helpers/kruize.py
  tests/scripts/helpers/list_datasources_json_schema.py
  tests/scripts/helpers/list_metadata_json_cluster_name_without_verbose_schema.py
  tests/scripts/helpers/list_metadata_json_schema.py
  tests/scripts/helpers/list_metadata_json_validate.py
  tests/scripts/helpers/list_metadata_json_verbose_true_schema.py
  tests/scripts/helpers/utils.py
  tests/scripts/local_monitoring_tests/Local_monitoring_tests.md
  tests/scripts/local_monitoring_tests/requirements.txt
  tests/scripts/local_monitoring_tests/rest_apis/test_import_metadata.py
  tests/scripts/local_monitoring_tests/rest_apis/test_list_metadata.py
  tests/scripts/remote_monitoring_tests/db_migration_test.md
  tests/scripts/remote_monitoring_tests/db_migration_test/db_migration_test.sh
  tests/scripts/remote_monitoring_tests/db_migration_test/db_migration_test_without_postgres_restart.sh
  tests/scripts/remote_monitoring_tests/db_migration_test/validate_reco_json.py
  tests/scripts/remote_monitoring_tests/fault_tolerant_tests/remote_monitoring_fault_tolerant_tests.sh
  tests/scripts/remote_monitoring_tests/requirements.txt
  tests/scripts/remote_monitoring_tests/scalability_test.md
  tests/scripts/remote_monitoring_tests/scale_test/parse_metrics.py
  tests/scripts/remote_monitoring_tests/scale_test/remote_monitoring_scale_test_bulk.sh
  tests/scripts/remote_monitoring_tests/scale_test/run_bulk_scalability_test.sh
  tests/scripts/remote_monitoring_tests/stress_test/remote_monitoring_stress_test.sh
  tests/test_plans/test_plan_rel_0.0.22.md
Labels: release
