Repository kruize/autotune, pull requests merged in 2024-05, with the labels that each got.

#1192 Fix memory format for local monitoring
  src/main/java/com/autotune/analyzer/recommendations/engine/RecommendationEngine.java
  src/main/java/com/autotune/utils/KruizeConstants.java
Labels: kruize-local

#1187 Include Local monitoring tests for Datasource APIs
  tests/README.md
  tests/scripts/common/common_functions.sh
  tests/scripts/functional_tests.sh
  tests/scripts/helpers/__init__.py
  tests/scripts/helpers/all_terms_list_reco_json_schema.py
  tests/scripts/helpers/fixtures.py
  tests/scripts/helpers/generate_datasource_json.py
  tests/scripts/helpers/generate_rm_jsons.py
  tests/scripts/helpers/import_metadata_json_schema.py
  tests/scripts/helpers/import_metadata_json_validate.py
  tests/scripts/helpers/kruize.py
  tests/scripts/helpers/list_datasources_json_schema.py
  tests/scripts/helpers/list_datasources_json_validate.py
  tests/scripts/helpers/list_reco_json_schema.py
  tests/scripts/helpers/list_reco_json_validate.py
  tests/scripts/helpers/long_term_list_reco_json_schema.py
  tests/scripts/helpers/medium_and_long_term_list_reco_json_schema.py
  tests/scripts/helpers/medium_term_list_reco_json_schema.py
  tests/scripts/helpers/short_and_long_term_list_reco_json_schema.py
  tests/scripts/helpers/short_and_medium_term_list_reco_json_schema.py
  tests/scripts/helpers/short_term_list_reco_json_schema.py
  tests/scripts/helpers/utils.py
  tests/scripts/local_monitoring_tests/Local_monitoring_tests.md
  tests/scripts/local_monitoring_tests/conftest.py
  tests/scripts/local_monitoring_tests/json_files/import_metadata.json
  tests/scripts/local_monitoring_tests/json_files/import_metadata_mandatory.json
  tests/scripts/local_monitoring_tests/json_files/import_metadata_template.json
  tests/scripts/local_monitoring_tests/json_files/resource_optimization_openshift.json
  tests/scripts/local_monitoring_tests/local_monitoring_tests.sh
  tests/scripts/local_monitoring_tests/pytest.ini
  tests/scripts/local_monitoring_tests/requirements.txt
  tests/scripts/local_monitoring_tests/rest_apis/test_import_metadata.py
  tests/scripts/local_monitoring_tests/rest_apis/test_list_datasources.py
  tests/scripts/remote_monitoring_tests/Remote_monitoring_tests.md
  tests/scripts/remote_monitoring_tests/fault_tolerant_tests/kruize_pod_restart_test.py
  tests/scripts/remote_monitoring_tests/rest_apis/test_create_experiment.py
  tests/scripts/remote_monitoring_tests/rest_apis/test_e2e_workflow.py
  tests/scripts/remote_monitoring_tests/rest_apis/test_list_recommendations.py
  tests/scripts/remote_monitoring_tests/rest_apis/test_update_recommendations.py
  tests/scripts/remote_monitoring_tests/rest_apis/test_update_results.py
  tests/test_autotune.sh
Labels: remote_monitoring, kruize-local

#1189 Fix Box Plots Issues
  src/main/java/com/autotune/analyzer/plots/PlotManager.java
  src/main/java/com/autotune/analyzer/recommendations/engine/RecommendationEngine.java
  src/main/java/com/autotune/analyzer/recommendations/model/CostBasedRecommendationModel.java
  src/main/java/com/autotune/analyzer/recommendations/model/PerformanceBasedRecommendationModel.java
Labels: bug, remote_monitoring

#1108 box plots data scripts
  manifests/crc/BYODB-installation/minikube/kruize-crc-minikube.yaml
  manifests/crc/BYODB-installation/openshift/kruize-crc-openshift.yaml
  manifests/crc/default-db-included-installation/minikube/kruize-crc-minikube.yaml
  manifests/crc/default-db-included-installation/openshift/kruize-crc-openshift.yaml
  tests/scripts/helpers/all_terms_list_reco_json_schema.py
  tests/scripts/helpers/list_reco_json_schema.py
  tests/scripts/helpers/long_term_list_reco_json_schema.py
  tests/scripts/helpers/medium_and_long_term_list_reco_json_schema.py
  tests/scripts/helpers/medium_term_list_reco_json_schema.py
  tests/scripts/helpers/short_and_long_term_list_reco_json_schema.py
  tests/scripts/helpers/short_and_medium_term_list_reco_json_schema.py
  tests/scripts/helpers/short_term_list_reco_json_schema.py
  tests/scripts/helpers/utils.py
  tests/scripts/remote_monitoring_tests/Remote_monitoring_tests.md
  tests/scripts/remote_monitoring_tests/rest_apis/test_e2e_workflow.py
  tests/scripts/remote_monitoring_tests/rest_apis/test_list_recommendations.py
  tests/scripts/remote_monitoring_tests/rest_apis/test_update_recommendations.py
Labels: remote_monitoring

#1174 Add Kruize local API documentation
  design/KruizeLocalAPI.md
Labels: remote_monitoring

#1195 Bump mvp_demo to version 0.0.22_mvp
  manifests/crc/BYODB-installation/minikube/kruize-crc-minikube.yaml
  manifests/crc/BYODB-installation/openshift/kruize-crc-openshift.yaml
  manifests/crc/default-db-included-installation/minikube/kruize-crc-minikube.yaml
  manifests/crc/default-db-included-installation/openshift/kruize-crc-openshift.yaml
  pom.xml
Labels: release

#1197 Merge mvp_demo (0.0.22_mvp) to master
  design/KruizeLocalAPI.md
  design/KruizePromQL.md
  manifests/crc/BYODB-installation/minikube/kruize-crc-minikube.yaml
  manifests/crc/BYODB-installation/openshift/kruize-crc-openshift.yaml
  manifests/crc/default-db-included-installation/minikube/kruize-crc-minikube.yaml
  manifests/crc/default-db-included-installation/openshift/kruize-crc-openshift.yaml
  pom.xml
  src/main/java/com/autotune/analyzer/plots/PlotManager.java
  src/main/java/com/autotune/analyzer/recommendations/engine/RecommendationEngine.java
  src/main/java/com/autotune/analyzer/recommendations/model/CostBasedRecommendationModel.java
  src/main/java/com/autotune/analyzer/recommendations/model/PerformanceBasedRecommendationModel.java
  src/main/java/com/autotune/utils/KruizeConstants.java
  src/main/java/com/autotune/utils/MetricsConfig.java
  tests/README.md
  tests/scripts/common/common_functions.sh
  tests/scripts/functional_tests.sh
  tests/scripts/helpers/__init__.py
  tests/scripts/helpers/all_terms_list_reco_json_schema.py
  tests/scripts/helpers/fixtures.py
  tests/scripts/helpers/generate_datasource_json.py
  tests/scripts/helpers/generate_rm_jsons.py
  tests/scripts/helpers/import_metadata_json_schema.py
  tests/scripts/helpers/import_metadata_json_validate.py
  tests/scripts/helpers/kruize.py
  tests/scripts/helpers/list_datasources_json_schema.py
  tests/scripts/helpers/list_datasources_json_validate.py
  tests/scripts/helpers/list_reco_json_schema.py
  tests/scripts/helpers/list_reco_json_validate.py
  tests/scripts/helpers/long_term_list_reco_json_schema.py
  tests/scripts/helpers/medium_and_long_term_list_reco_json_schema.py
  tests/scripts/helpers/medium_term_list_reco_json_schema.py
  tests/scripts/helpers/short_and_long_term_list_reco_json_schema.py
  tests/scripts/helpers/short_and_medium_term_list_reco_json_schema.py
  tests/scripts/helpers/short_term_list_reco_json_schema.py
  tests/scripts/helpers/utils.py
  tests/scripts/local_monitoring_tests/Local_monitoring_tests.md
  tests/scripts/local_monitoring_tests/conftest.py
  tests/scripts/local_monitoring_tests/json_files/import_metadata.json
  tests/scripts/local_monitoring_tests/json_files/import_metadata_mandatory.json
  tests/scripts/local_monitoring_tests/json_files/import_metadata_template.json
  tests/scripts/local_monitoring_tests/json_files/resource_optimization_openshift.json
  tests/scripts/local_monitoring_tests/local_monitoring_tests.sh
  tests/scripts/local_monitoring_tests/pytest.ini
  tests/scripts/local_monitoring_tests/requirements.txt
  tests/scripts/local_monitoring_tests/rest_apis/test_import_metadata.py
  tests/scripts/local_monitoring_tests/rest_apis/test_list_datasources.py
  tests/scripts/remote_monitoring_tests/Remote_monitoring_tests.md
  tests/scripts/remote_monitoring_tests/fault_tolerant_tests/kruize_pod_restart_test.py
  tests/scripts/remote_monitoring_tests/rest_apis/test_create_experiment.py
  tests/scripts/remote_monitoring_tests/rest_apis/test_e2e_workflow.py
  tests/scripts/remote_monitoring_tests/rest_apis/test_list_recommendations.py
  tests/scripts/remote_monitoring_tests/rest_apis/test_update_recommendations.py
  tests/scripts/remote_monitoring_tests/rest_apis/test_update_results.py
  tests/test_autotune.sh
  tests/test_plans/test_plan_rel_0.0.21.md
Labels: release

#1188 Logging success and failure logs for APIs
  src/main/java/com/autotune/analyzer/services/UpdateRecommendations.java
  src/main/java/com/autotune/analyzer/services/UpdateResults.java
  src/main/java/com/autotune/operator/KruizeDeploymentInfo.java
Labels: enhancement
