Repository kruize/autotune, pull requests merged in 2024-09, with the labels that each got.

#1223 Add support for Kubernetes workload type - 'job'
  src/main/java/com/autotune/analyzer/utils/AnalyzerConstants.java
  src/main/java/com/autotune/utils/Utils.java
  tests/scripts/helpers/list_reco_json_validate.py
  tests/scripts/remote_monitoring_tests/json_files/create_exp_job_type.json
  tests/scripts/remote_monitoring_tests/json_files/multiple_results_single_job_type_exp.json
  tests/scripts/remote_monitoring_tests/rest_apis/test_create_experiment.py
  tests/scripts/remote_monitoring_tests/rest_apis/test_list_recommendations.py
Labels: enhancement

#1276 Kruize Notification prod fix
  src/main/java/com/autotune/metrics/KruizeNotificationCollectionRegistry.java
  src/main/java/com/autotune/utils/KruizeConstants.java
Labels: remote_monitoring

#1271 Bump mvp release to 0.0.24_mvp
  manifests/crc/BYODB-installation/minikube/kruize-crc-minikube.yaml
  manifests/crc/BYODB-installation/openshift/kruize-crc-openshift.yaml
  manifests/crc/default-db-included-installation/minikube/kruize-crc-minikube.yaml
  manifests/crc/default-db-included-installation/openshift/kruize-crc-openshift.yaml
  pom.xml
Labels: release

#1288 Add Metric Profile JSON file in manifests
  manifests/autotune/performance-profiles/resource_optimization_local_monitoring.json
  manifests/autotune/performance-profiles/resource_optimization_local_monitoring.yaml
Labels: remote_monitoring, local_monitoring

#1249 Adding Queries For Namespace Recommendations
  manifests/autotune/performance-profiles/resource_optimization_local_monitoring.json
  manifests/autotune/performance-profiles/resource_optimization_local_monitoring.yaml
Labels: remote_monitoring

#1248 Adding Required Classes and Objects For Namespace Recommendations
  src/main/java/com/autotune/analyzer/recommendations/NamespaceRecommendations.java
  src/main/java/com/autotune/analyzer/serviceObjects/KubernetesAPIObject.java
  src/main/java/com/autotune/analyzer/serviceObjects/NamespaceAPIObject.java
  src/main/java/com/autotune/common/data/result/NamespaceData.java
  src/main/java/com/autotune/common/k8sObjects/K8sObject.java
  src/main/java/com/autotune/utils/KruizeConstants.java
Labels: remote_monitoring

#1283 Validate local monitoring recommendation values for end-to-end tests
  tests/scripts/helpers/list_reco_json_local_monitoring_schema.py
  tests/scripts/helpers/utils.py
  tests/scripts/local_monitoring_tests/rest_apis/test_local_monitoring_e2e_workflow.py
Labels: test, local_monitoring

#1278 Configure Openshift port for Prometheus service
  manifests/crc/BYODB-installation/openshift/kruize-crc-openshift.yaml
  manifests/crc/default-db-included-installation/openshift/kruize-crc-openshift.yaml
  src/main/java/com/autotune/common/datasource/prometheus/PrometheusDataOperatorImpl.java
  src/main/java/com/autotune/utils/KruizeConstants.java
Labels: local_monitoring

#1291 Refactor and include datasource manifest test
  manifests/autotune/performance-profiles/resource_optimization_local_monitoring.json
  tests/scripts/common/common_functions.sh
  tests/scripts/functional_tests.sh
  tests/scripts/helpers/kruize.py
  tests/scripts/helpers/utils.py
  tests/scripts/local_monitoring_tests/fault_tolerant_test/kruize_pod_restart_test.py
  tests/scripts/local_monitoring_tests/fault_tolerant_test/local_monitoring_fault_tolerant_tests.sh
  tests/scripts/local_monitoring_tests/json_files/create_tfb_db_exp.json
  tests/scripts/local_monitoring_tests/json_files/create_tfb_exp.json
  tests/scripts/local_monitoring_tests/json_files/resource_optimization_openshift.json
  tests/scripts/local_monitoring_tests/json_files/resource_optimization_openshift_metric_profile.json
  tests/scripts/local_monitoring_tests/local_monitoring_tests.sh
  tests/scripts/local_monitoring_tests/rest_apis/test_create_metric_profile.py
  tests/scripts/local_monitoring_tests/rest_apis/test_list_metric_profiles.py
  tests/scripts/local_monitoring_tests/rest_apis/test_local_monitoring_e2e_workflow.py
  tests/test_autotune.sh
Labels: test, local_monitoring

#1275 Adding Support for Namespace Recommendations
  src/main/java/com/autotune/analyzer/recommendations/engine/RecommendationEngine.java
  src/main/java/com/autotune/analyzer/recommendations/model/CostBasedRecommendationModel.java
  src/main/java/com/autotune/analyzer/recommendations/model/PerformanceBasedRecommendationModel.java
  src/main/java/com/autotune/analyzer/recommendations/model/RecommendationModel.java
  src/main/java/com/autotune/analyzer/recommendations/term/Terms.java
  src/main/java/com/autotune/analyzer/recommendations/utils/RecommendationUtils.java
  src/main/java/com/autotune/analyzer/serviceObjects/Converters.java
  src/main/java/com/autotune/analyzer/serviceObjects/KubernetesAPIObject.java
  src/main/java/com/autotune/analyzer/services/ListExperiments.java
  src/main/java/com/autotune/analyzer/utils/AnalyzerConstants.java
  src/main/java/com/autotune/analyzer/utils/AnalyzerErrorConstants.java
  src/main/java/com/autotune/common/k8sObjects/K8sObject.java
  src/main/java/com/autotune/database/helper/DBHelpers.java
  src/main/java/com/autotune/database/service/ExperimentDBService.java
  src/main/java/com/autotune/utils/KruizeConstants.java
Labels: remote_monitoring

#1289 Datasource authentication updates
  manifests/crc/BYODB-installation/openshift/kruize-crc-openshift.yaml
  manifests/crc/default-db-included-installation/openshift/kruize-crc-openshift.yaml
  migrations/kruize_local_ddl.sql
  src/main/java/com/autotune/analyzer/recommendations/engine/RecommendationEngine.java
  src/main/java/com/autotune/common/auth/APIKeyAuthenticationStrategy.java
  src/main/java/com/autotune/common/auth/AuthenticationConfig.java
  src/main/java/com/autotune/common/auth/AuthenticationStrategy.java
  src/main/java/com/autotune/common/auth/AuthenticationStrategyFactory.java
  src/main/java/com/autotune/common/auth/BasicAuthenticationStrategy.java
  src/main/java/com/autotune/common/auth/BearerAuthenticationStrategy.java
  src/main/java/com/autotune/common/auth/Credentials.java
  src/main/java/com/autotune/common/auth/OAuth2AuthenticationStrategy.java
  src/main/java/com/autotune/common/datasource/DataSourceCollection.java
  src/main/java/com/autotune/common/datasource/DataSourceInfo.java
  src/main/java/com/autotune/common/datasource/DataSourceMetadataOperator.java
  src/main/java/com/autotune/common/datasource/DataSourceOperator.java
  src/main/java/com/autotune/common/datasource/DataSourceOperatorImpl.java
  src/main/java/com/autotune/common/datasource/prometheus/PrometheusDataOperatorImpl.java
  src/main/java/com/autotune/common/utils/CommonUtils.java
  src/main/java/com/autotune/experimentManager/handler/MetricCollectionHandler.java
  src/main/java/com/autotune/utils/GenericRestApiClient.java
  src/main/java/com/autotune/utils/HttpUtils.java
  src/main/java/com/autotune/utils/KruizeConstants.java
Labels: enhancement, local_monitoring

#1294 Fix PR failures after 1289 merge
  src/main/java/com/autotune/analyzer/recommendations/engine/RecommendationEngine.java
Labels: bug

#1296 Fix issues while running kruize-demos
  manifests/crc/default-db-included-installation/openshift/kruize-crc-openshift.yaml
  src/main/java/com/autotune/analyzer/recommendations/engine/RecommendationEngine.java
  src/main/java/com/autotune/analyzer/services/CreateExperiment.java
  src/main/java/com/autotune/analyzer/services/DSMetadataService.java
  src/main/java/com/autotune/common/auth/AuthenticationStrategyFactory.java
  src/main/java/com/autotune/common/auth/NoAuthStrategy.java
  src/main/java/com/autotune/common/datasource/DataSourceCollection.java
  src/main/java/com/autotune/common/datasource/DataSourceInfo.java
  src/main/java/com/autotune/common/datasource/DataSourceOperatorImpl.java
  src/main/java/com/autotune/common/datasource/prometheus/PrometheusDataOperatorImpl.java
  src/main/java/com/autotune/common/utils/CommonUtils.java
  src/main/java/com/autotune/utils/GenericRestApiClient.java
  src/main/java/com/autotune/utils/KruizeConstants.java
Labels: bug

#1300 Include non-recording cpu usage queries into separate yaml
  manifests/autotune/performance-profiles/resource_optimization_local_monitoring_norecordingrules.json
  manifests/autotune/performance-profiles/resource_optimization_local_monitoring_norecordingrules.yaml
Labels: remote_monitoring

#1299 Updating Experiment Type in Create Experiment and List Recommendations
  design/KruizeLocalAPI.md
  migrations/kruize_local_ddl.sql
  src/main/java/com/autotune/analyzer/exceptions/FetchMetricsError.java
  src/main/java/com/autotune/analyzer/exceptions/InvalidExperimentType.java
  src/main/java/com/autotune/analyzer/kruizeObject/KruizeObject.java
  src/main/java/com/autotune/analyzer/recommendations/engine/RecommendationEngine.java
  src/main/java/com/autotune/analyzer/serviceObjects/Converters.java
  src/main/java/com/autotune/analyzer/serviceObjects/CreateExperimentAPIObject.java
  src/main/java/com/autotune/analyzer/serviceObjects/KubernetesAPIObject.java
  src/main/java/com/autotune/analyzer/serviceObjects/ListRecommendationsAPIObject.java
  src/main/java/com/autotune/analyzer/services/CreateExperiment.java
  src/main/java/com/autotune/analyzer/services/GenerateRecommendations.java
  src/main/java/com/autotune/analyzer/services/UpdateRecommendations.java
  src/main/java/com/autotune/analyzer/utils/AnalyzerErrorConstants.java
  src/main/java/com/autotune/analyzer/utils/ExperimentTypeAware.java
  src/main/java/com/autotune/analyzer/utils/ExperimentTypeUtil.java
  src/main/java/com/autotune/common/datasource/DataSourceOperatorImpl.java
  src/main/java/com/autotune/common/datasource/prometheus/PrometheusDataOperatorImpl.java
  src/main/java/com/autotune/common/k8sObjects/K8sObject.java
  src/main/java/com/autotune/database/dao/ExperimentDAOImpl.java
  src/main/java/com/autotune/database/helper/DBConstants.java
  src/main/java/com/autotune/database/helper/DBHelpers.java
  src/main/java/com/autotune/database/table/KruizeExperimentEntry.java
  src/main/java/com/autotune/database/table/KruizeRecommendationEntry.java
  src/main/java/com/autotune/utils/GenericRestApiClient.java
  src/main/java/com/autotune/utils/KruizeConstants.java
Labels: remote_monitoring

#1301 Updating Tests For Namespace Recommendations
  manifests/autotune/performance-profiles/resource_optimization_local_monitoring_norecordingrules.json
  tests/scripts/helpers/list_reco_json_local_monitoring_schema.py
  tests/scripts/helpers/utils.py
  tests/scripts/local_monitoring_tests/json_files/create_exp_template.json
  tests/scripts/local_monitoring_tests/json_files/create_multiple_namespace_exp.json
  tests/scripts/local_monitoring_tests/rest_apis/test_create_experiment.py
  tests/scripts/local_monitoring_tests/rest_apis/test_list_recommendations.py
  tests/scripts/local_monitoring_tests/rest_apis/test_local_monitoring_e2e_workflow.py
  tests/scripts/local_monitoring_tests/rest_apis/test_namespace_reco_e2e_workflow.py
Labels: remote_monitoring

#1305 Updating Local Monitoring Test
  tests/scripts/helpers/utils.py
  tests/scripts/local_monitoring_tests/rest_apis/test_list_recommendations.py
  tests/scripts/local_monitoring_tests/rest_apis/test_local_monitoring_e2e_workflow.py
  tests/scripts/local_monitoring_tests/rest_apis/test_namespace_reco_e2e_workflow.py
Labels: remote_monitoring

#1298 Bump mvp_demo to Kruize version 0.0.25_mvp
  manifests/crc/BYODB-installation/minikube/kruize-crc-minikube.yaml
  manifests/crc/BYODB-installation/openshift/kruize-crc-openshift.yaml
  manifests/crc/default-db-included-installation/aks/kruize-crc-aks.yaml
  manifests/crc/default-db-included-installation/minikube/kruize-crc-minikube.yaml
  manifests/crc/default-db-included-installation/openshift/kruize-crc-openshift.yaml
  pom.xml
Labels: release
