Repository kruize/autotune, pull requests merged in 2024-11, with the labels that each got.

#1368 Bulk api error handling with new Json
  design/BulkAPI.md
  src/main/java/com/autotune/analyzer/serviceObjects/BulkJobStatus.java
  src/main/java/com/autotune/analyzer/services/BulkService.java
  src/main/java/com/autotune/analyzer/workerimpl/BulkJobManager.java
  src/main/java/com/autotune/utils/GenericRestApiClient.java
  src/main/java/com/autotune/utils/KruizeConstants.java
Labels: kruize-local

#1358 Fix missing datasource issue on pod restart
  src/main/java/com/autotune/common/datasource/DataSourceCollection.java
  src/main/java/com/autotune/common/utils/CommonUtils.java
  src/main/java/com/autotune/utils/KruizeConstants.java
Labels: bug, remote_monitoring

#1369 Add Time Range Filter for Bulk API
  design/BulkAPI.md
  src/main/java/com/autotune/analyzer/workerimpl/BulkJobManager.java
  src/main/java/com/autotune/common/datasource/DataSourceMetadataOperator.java
  src/main/java/com/autotune/utils/KruizeConstants.java
Labels: enhancement, remote_monitoring

#1378 time_range fix
  src/main/java/com/autotune/analyzer/recommendations/engine/RecommendationEngine.java
  src/main/java/com/autotune/analyzer/recommendations/utils/RecommendationUtils.java
  src/main/java/com/autotune/common/datasource/DataSourceMetadataOperator.java
  src/main/java/com/autotune/utils/KruizeConstants.java
Labels: bug

#1311 Database updates for authentication
  migrations/kruize_local_ddl.sql
  src/main/java/com/autotune/common/auth/AuthType.java
  src/main/java/com/autotune/common/auth/AuthenticationConfig.java
  src/main/java/com/autotune/common/auth/AuthenticationStrategyFactory.java
  src/main/java/com/autotune/common/auth/Credentials.java
  src/main/java/com/autotune/common/data/ValidationOutputData.java
  src/main/java/com/autotune/common/datasource/DataSourceCollection.java
  src/main/java/com/autotune/common/datasource/DataSourceInfo.java
  src/main/java/com/autotune/common/datasource/DataSourceOperatorImpl.java
  src/main/java/com/autotune/database/dao/ExperimentDAO.java
  src/main/java/com/autotune/database/dao/ExperimentDAOImpl.java
  src/main/java/com/autotune/database/helper/DBHelpers.java
  src/main/java/com/autotune/database/init/KruizeHibernateUtil.java
  src/main/java/com/autotune/database/service/ExperimentDBService.java
  src/main/java/com/autotune/database/table/KruizeAuthenticationEntry.java
  src/main/java/com/autotune/database/table/KruizeDataSourceEntry.java
  src/main/java/com/autotune/utils/KruizeConstants.java
  src/main/java/com/autotune/utils/TrialHelpers.java
Labels: enhancement

#1381 Environment variable error found in the log
  src/main/java/com/autotune/analyzer/workerimpl/BulkJobManager.java
  src/main/java/com/autotune/operator/KruizeDeploymentInfo.java
  src/main/java/com/autotune/utils/KruizeConstants.java
Labels: bug

#1307 Add test script for authentication
  tests/scripts/common/common_functions.sh
  tests/scripts/functional_tests.sh
  tests/scripts/local_monitoring_tests/Local_monitoring_tests.md
  tests/scripts/local_monitoring_tests/authentication_tests.sh
Labels: test

#1388 Merge v0.2 changes to master
  .github/workflows/test-on-pr.yaml
  Dockerfile.autotune
  design/BulkAPI.md
  manifests/crc/BYODB-installation/minikube/kruize-crc-minikube.yaml
  manifests/crc/BYODB-installation/openshift/kruize-crc-openshift.yaml
  manifests/crc/default-db-included-installation/aks/kruize-crc-aks.yaml
  manifests/crc/default-db-included-installation/minikube/kruize-crc-minikube.yaml
  manifests/crc/default-db-included-installation/openshift/kruize-crc-openshift.yaml
  migrations/kruize_local_ddl.sql
  pom.xml
  src/main/java/com/autotune/Autotune.java
  src/main/java/com/autotune/analyzer/recommendations/engine/RecommendationEngine.java
  src/main/java/com/autotune/analyzer/recommendations/utils/RecommendationUtils.java
  src/main/java/com/autotune/analyzer/serviceObjects/BulkInput.java
  src/main/java/com/autotune/analyzer/serviceObjects/BulkJobStatus.java
  src/main/java/com/autotune/analyzer/services/BulkService.java
  src/main/java/com/autotune/analyzer/utils/AnalyzerConstants.java
  src/main/java/com/autotune/analyzer/workerimpl/BulkJobManager.java
  src/main/java/com/autotune/common/auth/AuthType.java
  src/main/java/com/autotune/common/auth/AuthenticationConfig.java
  src/main/java/com/autotune/common/auth/AuthenticationStrategyFactory.java
  src/main/java/com/autotune/common/auth/Credentials.java
  src/main/java/com/autotune/common/data/ValidationOutputData.java
  src/main/java/com/autotune/common/data/dataSourceQueries/DataSourceQueries.java
  src/main/java/com/autotune/common/datasource/DataSourceCollection.java
  src/main/java/com/autotune/common/datasource/DataSourceInfo.java
  src/main/java/com/autotune/common/datasource/DataSourceManager.java
  src/main/java/com/autotune/common/datasource/DataSourceMetadataOperator.java
  src/main/java/com/autotune/common/datasource/DataSourceOperator.java
  src/main/java/com/autotune/common/datasource/DataSourceOperatorImpl.java
  src/main/java/com/autotune/common/datasource/prometheus/PrometheusDataOperatorImpl.java
  src/main/java/com/autotune/common/utils/CommonUtils.java
  src/main/java/com/autotune/database/dao/ExperimentDAO.java
  src/main/java/com/autotune/database/dao/ExperimentDAOImpl.java
  src/main/java/com/autotune/database/helper/DBHelpers.java
  src/main/java/com/autotune/database/init/KruizeHibernateUtil.java
  src/main/java/com/autotune/database/service/ExperimentDBService.java
  src/main/java/com/autotune/database/table/KruizeAuthenticationEntry.java
  src/main/java/com/autotune/database/table/KruizeDataSourceEntry.java
  src/main/java/com/autotune/experimentManager/handler/MetricCollectionHandler.java
  src/main/java/com/autotune/operator/KruizeDeploymentInfo.java
  src/main/java/com/autotune/utils/GenericRestApiClient.java
  src/main/java/com/autotune/utils/KruizeConstants.java
  src/main/java/com/autotune/utils/TrialHelpers.java
  tests/scripts/common/common_functions.sh
  tests/scripts/functional_tests.sh
  tests/scripts/helpers/kruize.py
  tests/scripts/helpers/utils.py
  tests/scripts/local_monitoring_tests/Local_monitoring_tests.md
  tests/scripts/local_monitoring_tests/authentication_tests.sh
  tests/scripts/local_monitoring_tests/rest_apis/test_bulkAPI.py
  tests/test_plans/test_plan_rel_0.1.md
Labels: release

#1390 Ensure access to the variable is synchronized
  src/main/java/com/autotune/analyzer/serviceObjects/BulkJobStatus.java
Labels: bug

#1392 Merge 0.2 bug fix to master
  .github/workflows/test-on-push.yaml
  src/main/java/com/autotune/analyzer/serviceObjects/BulkJobStatus.java
Labels: bug

#1397 Update resource configuration in remote monitoring tests for openshift
  tests/scripts/common/common_functions.sh
Labels: bug

#1389 Add test plan & results for kruize rel 0.2
  tests/test_plans/test_plan_rel_0.2.md
Labels: test
