Repository kruize/autotune, pull requests merged in 2025-01, with the labels that each got.

#1463 [Kruize VPA Integration] Validation to Restrictions For Auto and Recreate Modes
  src/main/java/com/autotune/analyzer/experiment/ExperimentValidation.java
  src/main/java/com/autotune/analyzer/services/CreateExperiment.java
  src/main/java/com/autotune/analyzer/utils/AnalyzerErrorConstants.java
Labels: bug, remote_monitoring

#1452 KAMS - 1 : Add manifest changes to add cluster roles and bindings
  manifests/crc/default-db-included-installation/minikube/kruize-crc-minikube.yaml
  manifests/crc/default-db-included-installation/openshift/kruize-crc-openshift.yaml
Labels: recommendation, kruize-local, Accelerator

#1466 Adding Functionality to Dynamically Calculate Threshold Value For Minimum Time Required For Term
  src/main/java/com/autotune/analyzer/kruizeObject/KruizeObject.java
  src/main/java/com/autotune/utils/KruizeConstants.java
Labels: remote_monitoring

#1434 1. Add CRDs for MetadataProfile
  design/MetadataProfile.md
  manifests/autotune/metadata-profiles/bulk_cluster_metadata_local_monitoring.json
  manifests/autotune/metadata-profiles/bulk_cluster_metadata_local_monitoring.yaml
  manifests/autotune/metadata-profiles/cluster_metadata_local_monitoring.json
  manifests/autotune/metadata-profiles/cluster_metadata_local_monitoring.yaml
  manifests/autotune/metadata-profiles/kruize-metadata-profile-crd.yaml
  manifests/autotune/metadata-profiles/metadata-profile-template.yaml
Labels: enhancement, local_monitoring

#1440 2. Add abstractions for MetadataProfile
  src/main/java/com/autotune/analyzer/metadataProfiles/MetadataProfile.java
  src/main/java/com/autotune/analyzer/metadataProfiles/MetadataProfileValidation.java
  src/main/java/com/autotune/analyzer/metadataProfiles/utils/MetadataProfileUtil.java
  src/main/java/com/autotune/analyzer/utils/AnalyzerConstants.java
  src/main/java/com/autotune/analyzer/utils/AnalyzerErrorConstants.java
  src/main/java/com/autotune/utils/KruizeConstants.java
Labels: enhancement, local_monitoring

#1441 3. Add MetadataProfile database
  migrations/kruize_local_ddl.sql
  src/main/java/com/autotune/database/dao/ExperimentDAO.java
  src/main/java/com/autotune/database/dao/ExperimentDAOImpl.java
  src/main/java/com/autotune/database/helper/DBConstants.java
  src/main/java/com/autotune/database/init/KruizeHibernateUtil.java
  src/main/java/com/autotune/database/table/lm/KruizeLMMetadataProfileEntry.java
  src/main/java/com/autotune/utils/MetricsConfig.java
Labels: local_monitoring, database

#1472 Configure datasource via env
  design/BulkAPI.md
  src/main/java/com/autotune/common/auth/AuthenticationConfig.java
  src/main/java/com/autotune/common/auth/AuthenticationStrategyFactory.java
  src/main/java/com/autotune/common/auth/BearerAuthenticationStrategy.java
  src/main/java/com/autotune/common/auth/Credentials.java
  src/main/java/com/autotune/common/datasource/DataSourceCollection.java
  src/main/java/com/autotune/common/datasource/DataSourceMetadataOperator.java
  src/main/java/com/autotune/common/datasource/prometheus/PrometheusDataOperatorImpl.java
  src/main/java/com/autotune/common/utils/CommonUtils.java
  src/main/java/com/autotune/operator/KruizeDeploymentInfo.java
  src/main/java/com/autotune/utils/KruizeConstants.java
Labels: API

#1469 [Kruize VPA Integration] Adding Documentation For VPA
  design/AutoScalingModeAPI.md
Labels: documentation, remote_monitoring

#1470 [Kruize VPA Integration] Updating Default Model to Short Term Performance
  src/main/java/com/autotune/analyzer/recommendations/updater/vpa/VpaUpdaterImpl.java
Labels: remote_monitoring

#1485 bump version to V4
  .github/workflows/get-pr-number.yaml
  .github/workflows/rm-release-test.yaml
  .github/workflows/test-on-comment.yaml
  .github/workflows/test-on-pr.yaml
  .github/workflows/test-on-push.yaml
Labels: dependencies

#1479 Fix issue with Datasource in case of No-Auth config
  src/main/java/com/autotune/database/helper/DBHelpers.java
Labels: bug

#1481 Add MetadataProfileCollection and DB helpers
  migrations/kruize_local_ddl.sql
  src/main/java/com/autotune/Autotune.java
  src/main/java/com/autotune/analyzer/metadataProfiles/MetadataProfile.java
  src/main/java/com/autotune/analyzer/metadataProfiles/MetadataProfileCollection.java
  src/main/java/com/autotune/database/helper/DBHelpers.java
  src/main/java/com/autotune/database/service/ExperimentDBService.java
  src/main/java/com/autotune/database/table/lm/KruizeLMMetadataProfileEntry.java
  src/main/java/com/autotune/utils/KruizeConstants.java
Labels: enhancement, local_monitoring, database
